// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatcommon.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace Common {

  #region Enums
  public enum enChatChannel {
    None = 0,
    /// <summary>
    ///跨区
    /// </summary>
    Zone = 1,
    /// <summary>
    ///世界
    /// </summary>
    World = 2,
    /// <summary>
    ///队伍
    /// </summary>
    Team = 3,
    /// <summary>
    ///好友
    /// </summary>
    Friend = 4,
    Max = 5,
  }

  #endregion

  #region Messages
  /// <summary>
  ///SysTips
  /// </summary>
  public sealed class SysTipsParamItem : pb::IMessage {
    private static readonly pb::MessageParser<SysTipsParamItem> _parser = new pb::MessageParser<SysTipsParamItem>(() => new SysTipsParamItem());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SysTipsParamItem> Parser { get { return _parser; } }

    /// <summary>Field number for the "item" field.</summary>
    public const int ItemFieldNumber = 1;
    private global::Common.Item item_;
    /// <summary>
    ///道具参数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.Item Item {
      get { return item_; }
      set {
        item_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (item_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Item);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (item_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Item);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (item_ == null) {
              item_ = new global::Common.Item();
            }
            input.ReadMessage(item_);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///SysTips参数
  /// </summary>
  public sealed class SysTipsParam : pb::IMessage {
    private static readonly pb::MessageParser<SysTipsParam> _parser = new pb::MessageParser<SysTipsParam>(() => new SysTipsParam());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SysTipsParam> Parser { get { return _parser; } }

    /// <summary>Field number for the "strparam" field.</summary>
    public const int StrparamFieldNumber = 1;
    private pb::ByteString strparam_ = pb::ByteString.Empty;
    /// <summary>
    ///字符串参数(优先判此参数)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Strparam {
      get { return strparam_; }
      set {
        strparam_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "intparam" field.</summary>
    public const int IntparamFieldNumber = 2;
    private ulong intparam_;
    /// <summary>
    ///整形参数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Intparam {
      get { return intparam_; }
      set {
        intparam_ = value;
      }
    }

    /// <summary>Field number for the "itemparam" field.</summary>
    public const int ItemparamFieldNumber = 3;
    private global::Common.SysTipsParamItem itemparam_;
    /// <summary>
    ///道具参数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.SysTipsParamItem Itemparam {
      get { return itemparam_; }
      set {
        itemparam_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Strparam.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Strparam);
      }
      if (Intparam != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Intparam);
      }
      if (itemparam_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Itemparam);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Strparam.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Strparam);
      }
      if (Intparam != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Intparam);
      }
      if (itemparam_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Itemparam);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Strparam = input.ReadBytes();
            break;
          }
          case 16: {
            Intparam = input.ReadUInt64();
            break;
          }
          case 26: {
            if (itemparam_ == null) {
              itemparam_ = new global::Common.SysTipsParamItem();
            }
            input.ReadMessage(itemparam_);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///SysTips参数列表
  /// </summary>
  public sealed class SysTipsParamList : pb::IMessage {
    private static readonly pb::MessageParser<SysTipsParamList> _parser = new pb::MessageParser<SysTipsParamList>(() => new SysTipsParamList());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SysTipsParamList> Parser { get { return _parser; } }

    /// <summary>Field number for the "params" field.</summary>
    public const int ParamsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Common.SysTipsParam> _repeated_params_codec
        = pb::FieldCodec.ForMessage(10, global::Common.SysTipsParam.Parser);
    private readonly pbc::RepeatedField<global::Common.SysTipsParam> params_ = new pbc::RepeatedField<global::Common.SysTipsParam>();
    /// <summary>
    ///参数列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Common.SysTipsParam> Params {
      get { return params_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      params_.WriteTo(output, _repeated_params_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += params_.CalculateSize(_repeated_params_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            params_.AddEntriesFrom(input, _repeated_params_codec);
            break;
          }
        }
      }
    }

  }

  public sealed class ModuleChat : pb::IMessage {
    private static readonly pb::MessageParser<ModuleChat> _parser = new pb::MessageParser<ModuleChat>(() => new ModuleChat());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ModuleChat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
