// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Person;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DemoRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface DemoRoot : GPBRootObject
@end

#pragma mark - Person

typedef GPB_ENUM(Person_FieldNumber) {
  Person_FieldNumber_Name = 1,
  Person_FieldNumber_Id_p = 2,
  Person_FieldNumber_Email = 3,
};

GPB_FINAL @interface Person : GPBMessage

/** id */
@property(nonatomic, readwrite) int32_t id_p;

/** 姓名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 邮件 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

@end

#pragma mark - AddressBook

typedef GPB_ENUM(AddressBook_FieldNumber) {
  AddressBook_FieldNumber_PeopleArray = 1,
};

GPB_FINAL @interface AddressBook : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Person*> *peopleArray;
/** The number of items in @c peopleArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger peopleArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
