// Generated by UIComponentBinder.cs, but can't modifity it manualy!
using System;
using UnityEngine;
using UnityEngine.UI;
using Logic.Core;
using TMPro;

namespace Logic.UI {
    [Serializable]
    public partial class UI_CharacterPreview_Head_Layout : UILayoutBase {
        public ToggleEx toggle = null; // [0] Path: ""
        public UnityEngine.UI.Image careerIcon = null; // [1] Path: "Img"
        public UnityEngine.UI.Image careerName = null; // [2] Path: "Img_Career"

        protected override void Loaded() {
            this.toggle = binder.Find<ToggleEx>(0);
            this.careerIcon = binder.Find<UnityEngine.UI.Image>(1);
            this.careerName = binder.Find<UnityEngine.UI.Image>(2);
        }

#if UNITY_EDITOR
        protected override void FindByPath(UnityEngine.Transform transform, bool check = false) {
            if (!check) {
                this.toggle = transform.GetComponent<ToggleEx>();
                this.careerIcon = transform.Find("Img").GetComponent<UnityEngine.UI.Image>();
                this.careerName = transform.Find("Img_Career").GetComponent<UnityEngine.UI.Image>();
            }
            else {
                UnityEngine.Transform _t_ = null;
                this.toggle = transform.GetComponent<ToggleEx>();
                _t_ = transform.Find("Img");
                this.careerIcon = _t_ != null ? _t_.GetComponent<UnityEngine.UI.Image>() : null;
                _t_ = transform.Find("Img_Career");
                this.careerName = _t_ != null ? _t_.GetComponent<UnityEngine.UI.Image>() : null;
            }
        }
#endif
    }
}
