//Auto Generate Code
using Logic.Core;
using System.Collections.Generic;
using Table;
using Lib.AssetLoader;
using System.IO;
using UnityEngine;
using Lib.Core;

namespace Logic
{
	public static class CSVRegister
	{		
        //public static bool isFinished { get { return _csvCurrentLoading >= _csvCount; } }
        //public static float Progress { get { return _csvCurrentLoading / (float)_csvCount; } }
		//private static List<ITable> _loaders;
		//private static int _csvCount = 0;
		//private static int _csvCurrentLoading = -1;

        public static bool isFinished { get; private set; }
        public static float Progress { get; private set; }
		public static void Load()
		{
			Progress = 0f;

			CSVWordStyle.Load();
			Progress = 0.001798561f;
			CSVLanguage.Load();	//depends: CSVWordStyle;
			Progress = 0.003597122f;
			CSVTaskLanguage.Load();	//depends: CSVWordStyle;
			Progress = 0.005395683f;
			CSVWorldLevel.Load();
			Progress = 0.007194245f;
			CSVWelfareType.Load();
			Progress = 0.008992806f;
			CSVWelfareMenu.Load();
			Progress = 0.01079137f;
			CSVWeatherTime.Load();
			Progress = 0.01258993f;
			CSVWeatherSpecial.Load();
			Progress = 0.01438849f;
			CSVWeatherSeason.Load();
			Progress = 0.01618705f;
			CSVWeather.Load();
			Progress = 0.01798561f;
			CSVVitality.Load();
			Progress = 0.01978417f;
			CSVVideoType.Load();
			Progress = 0.02158273f;
			CSVUplifted.Load();
			Progress = 0.02338129f;
			CSVUpgradeEffect.Load();
			Progress = 0.02517986f;
			CSVUnlock.Load();
			Progress = 0.02697842f;
			CSVUIRule.Load();
			Progress = 0.02877698f;
			CSVUiRelation.Load();
			Progress = 0.03057554f;
			CSVTutorialSecondHeading.Load();
			Progress = 0.0323741f;
			CSVTutorialFirstHeading.Load();
			Progress = 0.03417266f;
			CSVTutorialDetails.Load();
			Progress = 0.03597122f;
			CSVTutorial.Load();
			Progress = 0.03776978f;
			CSVTutor.Load();
			Progress = 0.03956835f;
			CSVTtArenaWinAward.Load();
			Progress = 0.0413669f;
			CSVTtArenaSegmentInformation.Load();
			Progress = 0.04316547f;
			CSVTtArenaRankingAward.Load();
			Progress = 0.04496403f;
			CSVTtArenaRandAward.Load();
			Progress = 0.04676259f;
			CSVTtArenaMaxStars.Load();
			Progress = 0.04856115f;
			CSVTtArenaCumlativeRewards.Load();
			Progress = 0.05035971f;
			CSVTrialStage.Load();
			Progress = 0.05215827f;
			CSVTrialSkillBar.Load();
			Progress = 0.05395683f;
			CSVTrialPreSkill.Load();
			Progress = 0.0557554f;
			CSVTrialParameters.Load();
			Progress = 0.05755396f;
			CSVTrialLevelGrade.Load();
			Progress = 0.05935252f;
			CSVTrialCharacteristic.Load();
			Progress = 0.06115108f;
			CSVTrialBadge.Load();
			Progress = 0.06294964f;
			CSVTreasuresUnlock.Load();
			Progress = 0.0647482f;
			CSVTreasuresLevel.Load();
			Progress = 0.06654676f;
			CSVTreasures.Load();
			Progress = 0.06834532f;
			CSVTreasureRaider.Load();
			Progress = 0.07014389f;
			CSVTravellerAwakening.Load();
			Progress = 0.07194245f;
			CSVTransform.Load();
			Progress = 0.073741f;
			CSVTradeParam.Load();
			Progress = 0.07553957f;
			CSVTrade.Load();
			Progress = 0.07733813f;
			CSVTrack.Load();
			Progress = 0.07913669f;
			CSVTownType.Load();
			Progress = 0.08093525f;
			CSVTownTaskLibrary.Load();
			Progress = 0.08273381f;
			CSVTownTask.Load();
			Progress = 0.08453237f;
			CSVTownContributeLv.Load();
			Progress = 0.08633094f;
			CSVTownContributeAward.Load();
			Progress = 0.0881295f;
			CSVTitleSeries.Load();
			Progress = 0.08992806f;
			CSVTitleColumn.Load();
			Progress = 0.09172662f;
			CSVTitle.Load();
			Progress = 0.09352518f;
			CSVTipsLvl.Load();
			Progress = 0.09532374f;
			CSVTips.Load();
			Progress = 0.0971223f;
			CSVTianTiWinAward.Load();
			Progress = 0.09892087f;
			CSVTianTiTask.Load();
			Progress = 0.1007194f;
			CSVTianTiSegmentInformation.Load();
			Progress = 0.102518f;
			CSVTianTiRankingAward.Load();
			Progress = 0.1043165f;
			CSVTianTiCumlativeRewards.Load();
			Progress = 0.1061151f;
			CSVTerrorSeriesData.Load();
			Progress = 0.1079137f;
			CSVTerrorSeries.Load();
			Progress = 0.1097122f;
			CSVTemporary.Load();
			Progress = 0.1115108f;
			CSVTeamTarget.Load();
			Progress = 0.1133094f;
			CSVTeamLogo.Load();
			Progress = 0.1151079f;
			CSVTeam.Load();
			Progress = 0.1169065f;
			CSVTeaching.Load();
			Progress = 0.118705f;
			CSVTaskPage.Load();	//depends: CSVLanguage;
			Progress = 0.1205036f;
			CSVTaskLevelConfine.Load();
			Progress = 0.1223022f;
			CSVTaskGoal.Load();
			Progress = 0.1241007f;
			CSVTaskCategory.Load();	//depends: CSVTaskLanguage;CSVWordStyle;
			Progress = 0.1258993f;
			CSVTask.Load();
			Progress = 0.1276978f;
			CSVTalkChoose.Load();
			Progress = 0.1294964f;
			CSVTalentExchange.Load();
			Progress = 0.131295f;
			CSVTalent.Load();
			Progress = 0.1330935f;
			CSVSystemEffect.Load();
			Progress = 0.1348921f;
			CSVSynthesis.Load();
			Progress = 0.1366906f;
			CSVSwitchCondition.Load();
			Progress = 0.1384892f;
			CSVSurvivalRankReward.Load();
			Progress = 0.1402878f;
			CSVSurvivalHangupReward.Load();
			Progress = 0.1420863f;
			CSVSurvivalFightReward.Load();
			Progress = 0.1438849f;
			CSVSuitEffect.Load();
			Progress = 0.1456835f;
			CSVSuit.Load();
			Progress = 0.147482f;
			CSVSubtitle.Load();
			Progress = 0.1492806f;
			CSVSubmitPetCondition.Load();
			Progress = 0.1510791f;
			CSVSubmit.Load();
			Progress = 0.1528777f;
			CSVStoneStage.Load();
			Progress = 0.1546763f;
			CSVStoneLevel.Load();
			Progress = 0.1564748f;
			CSVStone.Load();
			Progress = 0.1582734f;
			CSVStatus.Load();
			Progress = 0.1600719f;
			CSVStageReward.Load();
			Progress = 0.1618705f;
			CSVSpecialGoldPetExchange.Load();
			Progress = 0.1636691f;
			CSVSpecialGoldPetAppointExchange.Load();
			Progress = 0.1654676f;
			CSVSound.Load();
			Progress = 0.1672662f;
			CSVSoulBeadUnlock.Load();
			Progress = 0.1690647f;
			CSVSoulBeadSkill.Load();
			Progress = 0.1708633f;
			CSVSoulBeadPetAddexp.Load();
			Progress = 0.1726619f;
			CSVSoulBead.Load();
			Progress = 0.1744604f;
			CSVSlotUpgrade.Load();
			Progress = 0.176259f;
			CSVSkillSE.Load();
			Progress = 0.1780576f;
			CSVSinglePay.Load();
			Progress = 0.1798561f;
			CSVSigninRewardModel.Load();
			Progress = 0.1816547f;
			CSVSigninReward.Load();
			Progress = 0.1834532f;
			CSVSignActivity.Load();
			Progress = 0.1852518f;
			CSVSign.Load();
			Progress = 0.1870504f;
			CSVShopItem.Load();
			Progress = 0.1888489f;
			CSVShop.Load();
			Progress = 0.1906475f;
			CSVShock.Load();
			Progress = 0.192446f;
			CSVSEState.Load();
			Progress = 0.1942446f;
			CSVSeekItem.Load();
			Progress = 0.1960432f;
			CSVSceneNubber.Load();
			Progress = 0.1978417f;
			CSVSavingsBank.Load();
			Progress = 0.1996403f;
			CSVRuneTypeID.Load();
			Progress = 0.2014388f;
			CSVRuneSynthetise.Load();
			Progress = 0.2032374f;
			CSVRuneSlot.Load();
			Progress = 0.205036f;
			CSVRuneLvlID.Load();
			Progress = 0.2068345f;
			CSVRuneInfo.Load();
			Progress = 0.2086331f;
			CSVRule.Load();
			Progress = 0.2104317f;
			CSVRobotName.Load();
			Progress = 0.2122302f;
			CSVRobotList.Load();
			Progress = 0.2140288f;
			CSVRobotAttr.Load();
			Progress = 0.2158273f;
			CSVReturnSign.Load();
			Progress = 0.2176259f;
			CSVReturnShop.Load();
			Progress = 0.2194245f;
			CSVReturnRecover.Load();
			Progress = 0.221223f;
			CSVReturnParam.Load();
			Progress = 0.2230216f;
			CSVReturnMenu.Load();
			Progress = 0.2248201f;
			CSVReturnGifts.Load();
			Progress = 0.2266187f;
			CSVReturnCommodity.Load();
			Progress = 0.2284173f;
			CSVReturnChanllengeTask.Load();
			Progress = 0.2302158f;
			CSVReturnChanllengeIntegral.Load();
			Progress = 0.2320144f;
			CSVReturnArdentReward.Load();
			Progress = 0.2338129f;
			CSVReturnArdent.Load();
			Progress = 0.2356115f;
			CSVResolving.Load();
			Progress = 0.2374101f;
			CSVRedEnvelopRain.Load();
			Progress = 0.2392086f;
			CSVRechargeSelection.Load();
			Progress = 0.2410072f;
			CSVRebuildExpend.Load();
			Progress = 0.2428057f;
			CSVRanklistsort.Load();
			Progress = 0.2446043f;
			CSVRanklistset.Load();
			Progress = 0.2464029f;
			CSVRanklistmain.Load();
			Progress = 0.2482014f;
			CSVRandomSkillLibrary.Load();
			Progress = 0.25f;
			CSVRaceSkillType.Load();
			Progress = 0.2517986f;
			CSVRaceDepartmentResearch.Load();
			Progress = 0.2535971f;
			CSVRaceChangeSkill.Load();
			Progress = 0.2553957f;
			CSVRaceChangeResearch.Load();
			Progress = 0.2571943f;
			CSVRaceChangeGroup.Load();
			Progress = 0.2589928f;
			CSVRaceChangeCard.Load();
			Progress = 0.2607914f;
			CSVQuestionnaire.Load();
			Progress = 0.2625899f;
			CSVQuestDailyControl.Load();
			Progress = 0.2643885f;
			CSVQualityParameter.Load();
			Progress = 0.266187f;
			CSVPublicityMap.Load();
			Progress = 0.2679856f;
			CSVPromptBox.Load();
			Progress = 0.2697842f;
			CSVPromoteCareer.Load();
			Progress = 0.2715827f;
			CSVPrivilege.Load();
			Progress = 0.2733813f;
			CSVPositionPoint.Load();
			Progress = 0.2751799f;
			CSVPKMatch.Load();
			Progress = 0.2769784f;
			CSVPetRemake.Load();
			Progress = 0.278777f;
			CSVPetRelease.Load();
			Progress = 0.2805755f;
			CSVPetNewTemplate.Load();
			Progress = 0.2823741f;
			CSVPetNewSkillSummary.Load();
			Progress = 0.2841727f;
			CSVPetNewSkillSort.Load();
			Progress = 0.2859712f;
			CSVPetNewSkillsLv.Load();
			Progress = 0.2877698f;
			CSVPetNewShowFilter.Load();
			Progress = 0.2895683f;
			CSVPetNewSeal.Load();
			Progress = 0.2913669f;
			CSVPetNewReBuild.Load();
			Progress = 0.2931655f;
			CSVPetNewParam.Load();
			Progress = 0.294964f;
			CSVPetNewMapRarity.Load();
			Progress = 0.2967626f;
			CSVPetNewlv.Load();
			Progress = 0.2985612f;
			CSVPetNewLoyaty.Load();
			Progress = 0.3003597f;
			CSVPetNewLoveUp.Load();
			Progress = 0.3021583f;
			CSVPetNewIsMount.Load();
			Progress = 0.3039568f;
			CSVPetNewExchange.Load();
			Progress = 0.3057554f;
			CSVPetNewEnhance.Load();
			Progress = 0.3075539f;
			CSVPetNewAreaControl.Load();
			Progress = 0.3093525f;
			CSVPetNew.Load();
			Progress = 0.3111511f;
			CSVPetMountStrengthen.Load();
			Progress = 0.3129496f;
			CSVPetMountAttr.Load();
			Progress = 0.3147482f;
			CSVPetMount.Load();
			Progress = 0.3165468f;
			CSVPetFashion.Load();
			Progress = 0.3183453f;
			CSVPetexploreTaskGroup.Load();
			Progress = 0.3201439f;
			CSVPetexploreReward.Load();
			Progress = 0.3219424f;
			CSVPetEquipSuitSkill.Load();
			Progress = 0.323741f;
			CSVPetEquipSuitAppearance.Load();
			Progress = 0.3255396f;
			CSVPetEquipQualityParameter.Load();
			Progress = 0.3273381f;
			CSVPetEquipQuality.Load();
			Progress = 0.3291367f;
			CSVPetEquipEffect.Load();
			Progress = 0.3309352f;
			CSVPetEquipAttr.Load();
			Progress = 0.3327338f;
			CSVPetEquip.Load();
			Progress = 0.3345324f;
			CSVPetBank.Load();
			Progress = 0.3363309f;
			CSVPedigreedTaskGroup.Load();
			Progress = 0.3381295f;
			CSVPedigreedParameter.Load();
			Progress = 0.3399281f;
			CSVPedigreedDraw.Load();
			Progress = 0.3417266f;
			CSVPassiveSkillInfo.Load();
			Progress = 0.3435252f;
			CSVPassiveSkill.Load();
			Progress = 0.3453237f;
			CSVPartnerSkill.Load();
			Progress = 0.3471223f;
			CSVPartnerQuality.Load();
			Progress = 0.3489209f;
			CSVPartnerOccupation.Load();
			Progress = 0.3507194f;
			CSVPartnerLevel.Load();
			Progress = 0.352518f;
			CSVPartnerBelonging.Load();
			Progress = 0.3543165f;
			CSVPartner.Load();
			Progress = 0.3561151f;
			CSVParam.Load();
			Progress = 0.3579137f;
			CSVOrnamentsUpgrade.Load();
			Progress = 0.3597122f;
			CSVOrnamentsType.Load();
			Progress = 0.3615108f;
			CSVOrnamentsSkill.Load();
			Progress = 0.3633094f;
			CSVOrnamentsAttributes.Load();
			Progress = 0.3651079f;
			CSVOperationalActivityRuler.Load();
			Progress = 0.3669065f;
			CSVOperatereward.Load();
			Progress = 0.368705f;
			CSVOpenUi.Load();
			Progress = 0.3705036f;
			CSVOneCoinLottey.Load();
			Progress = 0.3723021f;
			CSVNubber.Load();
			Progress = 0.3741007f;
			CSVNpcPathFinding.Load();
			Progress = 0.3758993f;
			CSVNPCOccupation.Load();
			Progress = 0.3776979f;
			CSVNPCMood.Load();
			Progress = 0.3794964f;
			CSVNpcLanguage.Load();	//depends: CSVWordStyle;
			Progress = 0.381295f;
			CSVNPCHealth.Load();
			Progress = 0.3830935f;
			CSVNPCHead.Load();
			Progress = 0.3848921f;
			CSVNpcFunctionData.Load();
			Progress = 0.3866906f;
			CSVNPCFavorabilityStage.Load();
			Progress = 0.3884892f;
			CSVNPCFavorability.Load();
			Progress = 0.3902878f;
			CSVNPCDisease.Load();
			Progress = 0.3920863f;
			CSVNPCCharacter.Load();
			Progress = 0.3938849f;
			CSVNpc.Load();
			Progress = 0.3956835f;
			CSVNien_Presonal_Rank.Load();
			Progress = 0.397482f;
			CSVNien_Parameters.Load();
			Progress = 0.3992806f;
			CSVNien_Enemy_Gropu.Load();
			Progress = 0.4010791f;
			CSVNien_Damage_Accumulate.Load();
			Progress = 0.4028777f;
			CSVNienPresonalRank.Load();
			Progress = 0.4046763f;
			CSVNienParameters.Load();
			Progress = 0.4064748f;
			CSVNienEnemyGropu.Load();
			Progress = 0.4082734f;
			CSVNienDamageAccumulate.Load();
			Progress = 0.4100719f;
			CSVNewBiographySeries.Load();
			Progress = 0.4118705f;
			CSVNaviMap.Load();
			Progress = 0.4136691f;
			CSVMoodSymbol.Load();
			Progress = 0.4154676f;
			CSVMonthCard.Load();
			Progress = 0.4172662f;
			CSVMonsterPvp.Load();
			Progress = 0.4190648f;
			CSVMonsterAttribute.Load();
			Progress = 0.4208633f;
			CSVMonster.Load();
			Progress = 0.4226619f;
			CSVMoneyShow.Load();
			Progress = 0.4244604f;
			CSVMoliSpirit.Load();
			Progress = 0.426259f;
			CSVMerchantFleetTask.Load();
			Progress = 0.4280576f;
			CSVMerchantFleetLevel.Load();
			Progress = 0.4298561f;
			CSVMemoryPieces.Load();
			Progress = 0.4316547f;
			CSVMatch.Load();
			Progress = 0.4334532f;
			CSVMapInfo.Load();
			Progress = 0.4352518f;
			CSVMapExplorationReward.Load();
			Progress = 0.4370504f;
			CSVMapExplorationMark.Load();
			Progress = 0.4388489f;
			CSVMapBitsInfo.Load();
			Progress = 0.4406475f;
			CSVMall.Load();
			Progress = 0.4424461f;
			CSVMail.Load();
			Progress = 0.4442446f;
			CSVLossTipsBanList.Load();
			Progress = 0.4460432f;
			CSVLittleGame_OneTOuchDraw.Load();
			Progress = 0.4478417f;
			CSVLittleGame_Elimination.Load();
			Progress = 0.4496403f;
			CSVLifeSkillRank.Load();
			Progress = 0.4514388f;
			CSVLifeSkillLevel.Load();
			Progress = 0.4532374f;
			CSVLifeSkill.Load();
			Progress = 0.455036f;
			CSVLevelName.Load();
			Progress = 0.4568345f;
			CSVLevelGift.Load();
			Progress = 0.4586331f;
			CSVJewelRecommend.Load();
			Progress = 0.4604317f;
			CSVJewel.Load();
			Progress = 0.4622302f;
			CSVItemSource.Load();
			Progress = 0.4640288f;
			CSVItemFun.Load();
			Progress = 0.4658273f;
			CSVItem.Load();
			Progress = 0.4676259f;
			CSVIsland.Load();
			Progress = 0.4694245f;
			CSVInterfaceBubble.Load();
			Progress = 0.471223f;
			CSVInteractivePerform.Load();
			Progress = 0.4730216f;
			CSVInstanceParam.Load();
			Progress = 0.4748201f;
			CSVInstanceDaily.Load();
			Progress = 0.4766187f;
			CSVInstance.Load();
			Progress = 0.4784173f;
			CSVIndustryTask.Load();
			Progress = 0.4802158f;
			CSVIndustryActivity.Load();
			Progress = 0.4820144f;
			CSVImprintUpgrade.Load();
			Progress = 0.483813f;
			CSVImprintNode.Load();
			Progress = 0.4856115f;
			CSVImprintLabel.Load();
			Progress = 0.4874101f;
			CSVIDIP.Load();
			Progress = 0.4892086f;
			CSVIconConfigure.Load();
			Progress = 0.4910072f;
			CSVHundredChapter.Load();
			Progress = 0.4928057f;
			CSVHotKey.Load();
			Progress = 0.4946043f;
			CSVHorn.Load();	//depends: CSVWordStyle;
			Progress = 0.4964029f;
			CSVHeadframe.Load();
			Progress = 0.4982014f;
			CSVHead.Load();
			Progress = 0.5f;
			CSVHangupParam.Load();
			Progress = 0.5017986f;
			CSVHangupLayerStage.Load();
			Progress = 0.5035971f;
			CSVHangup.Load();
			Progress = 0.5053957f;
			CSVGuideTip.Load();
			Progress = 0.5071942f;
			CSVGuideModel.Load();
			Progress = 0.5089928f;
			CSVGuideGroup.Load();
			Progress = 0.5107914f;
			CSVGuideEffect.Load();
			Progress = 0.5125899f;
			CSVGuideCondition.Load();
			Progress = 0.5143885f;
			CSVGuideArrow.Load();
			Progress = 0.5161871f;
			CSVGuide.Load();
			Progress = 0.5179856f;
			CSVGrowthFund.Load();
			Progress = 0.5197842f;
			CSVGreen.Load();
			Progress = 0.5215827f;
			CSVGoldPetExchange.Load();
			Progress = 0.5233813f;
			CSVGoddessTopic.Load();
			Progress = 0.5251799f;
			CSVGoddessSelect.Load();
			Progress = 0.5269784f;
			CSVGoddessGift.Load();
			Progress = 0.528777f;
			CSVGoddessEnd.Load();
			Progress = 0.5305755f;
			CSVGMMail.Load();
			Progress = 0.5323741f;
			CSVGleanings.Load();
			Progress = 0.5341727f;
			CSVGenus.Load();
			Progress = 0.5359712f;
			CSVFunForeshow.Load();
			Progress = 0.5377698f;
			CSVFunctionOpen.Load();
			Progress = 0.5395684f;
			CSVFunctionGroup.Load();
			Progress = 0.5413669f;
			CSVFunction.Load();
			Progress = 0.5431654f;
			CSVFriendSendItem.Load();
			Progress = 0.544964f;
			CSVFriendSearch.Load();
			Progress = 0.5467626f;
			CSVFriendIntimacy.Load();
			Progress = 0.5485612f;
			CSVFormulaSelect.Load();
			Progress = 0.5503597f;
			CSVFormulaParam.Load();
			Progress = 0.5521583f;
			CSVFormula.Load();
			Progress = 0.5539568f;
			CSVFoodIsShow.Load();
			Progress = 0.5557554f;
			CSVFoodAtlas.Load();
			Progress = 0.5575539f;
			CSVFirstCharge.Load();
			Progress = 0.5593525f;
			CSVFestivalTask.Load();
			Progress = 0.5611511f;
			CSVFavorabilityStamina.Load();
			Progress = 0.5629497f;
			CSVFavorabilityStageName.Load();
			Progress = 0.5647482f;
			CSVFavorabilityPlaceReward.Load();
			Progress = 0.5665467f;
			CSVFavorabilityGiftType.Load();
			Progress = 0.5683453f;
			CSVFavorabilityGift.Load();
			Progress = 0.5701439f;
			CSVFavorabilityBehavior.Load();
			Progress = 0.5719424f;
			CSVFavorabilityBanquet.Load();
			Progress = 0.573741f;
			CSVFashionWeaponModel.Load();
			Progress = 0.5755396f;
			CSVFashionWeapon.Load();
			Progress = 0.5773382f;
			CSVFashionSuit.Load();
			Progress = 0.5791367f;
			CSVFashionScroe.Load();
			Progress = 0.5809352f;
			CSVFashionModel.Load();
			Progress = 0.5827338f;
			CSVFashionIcon.Load();
			Progress = 0.5845324f;
			CSVFashionDraw.Load();
			Progress = 0.586331f;
			CSVFashionColour.Load();
			Progress = 0.5881295f;
			CSVFashionClothes.Load();
			Progress = 0.589928f;
			CSVFashionAttr.Load();
			Progress = 0.5917266f;
			CSVFashionActivity.Load();
			Progress = 0.5935252f;
			CSVFashionAccessory.Load();
			Progress = 0.5953237f;
			CSVFamilySkillUp.Load();
			Progress = 0.5971223f;
			CSVFamilyResBattleTeam.Load();
			Progress = 0.5989209f;
			CSVFamilyResBattleState.Load();
			Progress = 0.6007195f;
			CSVFamilyResBattleResult.Load();
			Progress = 0.602518f;
			CSVFamilyResBattleResParameter.Load();
			Progress = 0.6043165f;
			CSVFamilyResBattleParameter.Load();
			Progress = 0.6061151f;
			CSVFamilyResBattleCombatParameter.Load();
			Progress = 0.6079137f;
			CSVFamilyResBattleCamp.Load();
			Progress = 0.6097122f;
			CSVFamilyReception.Load();
			Progress = 0.6115108f;
			CSVFamilyProsperity.Load();
			Progress = 0.6133093f;
			CSVFamilyProhibitionMerger.Load();
			Progress = 0.6151079f;
			CSVFamilyPostAuthority.Load();
			Progress = 0.6169065f;
			CSVFamilyPetType.Load();
			Progress = 0.618705f;
			CSVFamilyPetTrainingStarReward.Load();
			Progress = 0.6205036f;
			CSVFamilyPetTrainingRankReward.Load();
			Progress = 0.6223022f;
			CSVFamilyPetMood.Load();
			Progress = 0.6241007f;
			CSVFamilyPetHealth.Load();
			Progress = 0.6258993f;
			CSVFamilyPetFood.Load();
			Progress = 0.6276978f;
			CSVFamilyPet.Load();
			Progress = 0.6294964f;
			CSVFamilyPacketSection.Load();
			Progress = 0.631295f;
			CSVFamilyPacketLimit.Load();
			Progress = 0.6330935f;
			CSVFamilyPacket.Load();
			Progress = 0.6348921f;
			CSVFamilyItem.Load();
			Progress = 0.6366907f;
			CSVFamilyFight.Load();
			Progress = 0.6384892f;
			CSVFamilyDonateTime.Load();
			Progress = 0.6402878f;
			CSVFamilyDonate.Load();
			Progress = 0.6420863f;
			CSVFamilyBossRankReward.Load();
			Progress = 0.6438849f;
			CSVFamilyBossParam.Load();
			Progress = 0.6456835f;
			CSVFamilyBossFamilyReward.Load();
			Progress = 0.647482f;
			CSVFamilyBonus.Load();
			Progress = 0.6492805f;
			CSVFamilyAuctionDrop.Load();
			Progress = 0.6510791f;
			CSVFamilyAuctionAward.Load();
			Progress = 0.6528777f;
			CSVFamilyAuctionAct.Load();
			Progress = 0.6546763f;
			CSVFamilyAuction.Load();
			Progress = 0.6564748f;
			CSVFamilyAthleticsWinAward.Load();
			Progress = 0.6582734f;
			CSVFamilyAthleticsRankReset.Load();
			Progress = 0.660072f;
			CSVFamilyAthleticsRankAward.Load();
			Progress = 0.6618705f;
			CSVFamilyAthleticsParameter.Load();
			Progress = 0.663669f;
			CSVFamilyAthleticsInspireBuff.Load();
			Progress = 0.6654676f;
			CSVFamilyAthleticsInspireAward.Load();
			Progress = 0.6672662f;
			CSVFamilyArchitectureEffect.Load();
			Progress = 0.6690648f;
			CSVFamilyArchitecture.Load();
			Progress = 0.6708633f;
			CSVFamilyActive.Load();
			Progress = 0.6726618f;
			CSVFameRank.Load();
			Progress = 0.6744604f;
			CSVFameAddition.Load();
			Progress = 0.676259f;
			CSVexpRetrieve.Load();
			Progress = 0.6780576f;
			CSVExploringSkill.Load();
			Progress = 0.6798561f;
			CSVExperienceLevel.Load();
			Progress = 0.6816547f;
			CSVExperienceAttrRank.Load();
			Progress = 0.6834533f;
			CSVExperienceAttr.Load();
			Progress = 0.6852518f;
			CSVExchangeItem.Load();
			Progress = 0.6870503f;
			CSVErrorCode.Load();
			Progress = 0.6888489f;
			CSVEquipmentRebuild.Load();
			Progress = 0.6906475f;
			CSVEquipmentParameter.Load();
			Progress = 0.6924461f;
			CSVEquipmentEffect.Load();
			Progress = 0.6942446f;
			CSVEquipment.Load();
			Progress = 0.6960432f;
			CSVElementAttributes.Load();
			Progress = 0.6978417f;
			CSVEffect.Load();
			Progress = 0.6996403f;
			CSVEditorMap.Load();
			Progress = 0.7014388f;
			CSVDynamicAttribute.Load();
			Progress = 0.7032374f;
			CSVDubbing.Load();
			Progress = 0.705036f;
			CSVDrop.Load();
			Progress = 0.7068346f;
			CSVDressUnlock.Load();
			Progress = 0.7086331f;
			CSVDomesticationTask.Load();
			Progress = 0.7104316f;
			CSVDomesticationRank.Load();
			Progress = 0.7122302f;
			CSVDomesticationEffect.Load();
			Progress = 0.7140288f;
			CSVDialogueLanguage.Load();	//depends: CSVWordStyle;
			Progress = 0.7158273f;
			CSVDialogue.Load();
			Progress = 0.7176259f;
			CSVDevice.Load();
			Progress = 0.7194245f;
			CSVDetect.Load();
			Progress = 0.721223f;
			CSVDeliver.Load();
			Progress = 0.7230216f;
			CSVDecisiveArenaRankingRedward.Load();
			Progress = 0.7248201f;
			CSVDecisiveArenaParam.Load();
			Progress = 0.7266187f;
			CSVDamageShowType.Load();
			Progress = 0.7284173f;
			CSVDamageShowConfig.Load();
			Progress = 0.7302158f;
			CSVDaliyPacks.Load();
			Progress = 0.7320144f;
			CSVDailyActivityWeek.Load();
			Progress = 0.7338129f;
			CSVDailyActivityShow.Load();
			Progress = 0.7356115f;
			CSVDailyActivityReward.Load();
			Progress = 0.7374101f;
			CSVDailyActivityPush.Load();
			Progress = 0.7392086f;
			CSVDailyActivity.Load();
			Progress = 0.7410072f;
			CSVCutSceneSubTitle.Load();
			Progress = 0.7428058f;
			CSVCutScene.Load();
			Progress = 0.7446043f;
			CSVCustomizeBag.Load();
			Progress = 0.7464029f;
			CSVCumulativeReward.Load();
			Progress = 0.7482014f;
			CSVCookLv.Load();
			Progress = 0.75f;
			CSVCookFunction.Load();
			Progress = 0.7517986f;
			CSVCookBookReward.Load();
			Progress = 0.7535971f;
			CSVCookAttr.Load();
			Progress = 0.7553957f;
			CSVCook.Load();
			Progress = 0.7571942f;
			CSVConditionalGift.Load();
			Progress = 0.7589928f;
			CSVComposeMenu.Load();
			Progress = 0.7607914f;
			CSVCompose.Load();
			Progress = 0.7625899f;
			CSVCommodityList.Load();
			Progress = 0.7643885f;
			CSVCommodityCategory.Load();
			Progress = 0.7661871f;
			CSVCommodity.Load();
			Progress = 0.7679856f;
			CSVCommand.Load();
			Progress = 0.7697842f;
			CSVCollectionProcess.Load();
			Progress = 0.7715827f;
			CSVCollection.Load();
			Progress = 0.7733813f;
			CSVCode.Load();
			Progress = 0.7751799f;
			CSVClueTask.Load();
			Progress = 0.7769784f;
			CSVCluePhasedTasksGroup.Load();
			Progress = 0.778777f;
			CSVClueDetectiveLevel.Load();
			Progress = 0.7805755f;
			CSVClueAdventureLevel.Load();
			Progress = 0.7823741f;
			CSVClassicBoss.Load();
			Progress = 0.7841727f;
			CSVChronology.Load();
			Progress = 0.7859712f;
			CSVChoseTargetLimit.Load();
			Progress = 0.7877698f;
			CSVChoseSkillLimit.Load();
			Progress = 0.7895684f;
			CSVCheckseq.Load();
			Progress = 0.7913669f;
			CSVChatWord.Load();
			Progress = 0.7931654f;
			CSVChatframe.Load();
			Progress = 0.794964f;
			CSVChatBlackIndustry.Load();
			Progress = 0.7967626f;
			CSVChatBack.Load();
			Progress = 0.7985612f;
			CSVChargeList.Load();
			Progress = 0.8003597f;
			CSVCharacterWeapon.Load();
			Progress = 0.8021583f;
			CSVCharacterHead.Load();
			Progress = 0.8039568f;
			CSVCharacterAttribute.Load();
			Progress = 0.8057554f;
			CSVCharacter.Load();
			Progress = 0.8075539f;
			CSVChapterSysTask.Load();
			Progress = 0.8093525f;
			CSVChapterInfo.Load();
			Progress = 0.8111511f;
			CSVChapterFunctionList.Load();
			Progress = 0.8129497f;
			CSVChapter.Load();
			Progress = 0.8147482f;
			CSVChaosAttr.Load();
			Progress = 0.8165467f;
			CSVChallengeLevel.Load();
			Progress = 0.8183453f;
			CSVChallengeArenaRankAward.Load();
			Progress = 0.8201439f;
			CSVChallengeArenaParameter.Load();
			Progress = 0.8219424f;
			CSVCareerTeaching.Load();
			Progress = 0.823741f;
			CSVCareerChange.Load();
			Progress = 0.8255396f;
			CSVCareer.Load();
			Progress = 0.8273382f;
			CSVCaptainPoint.Load();
			Progress = 0.8291367f;
			CSVCampInformation.Load();
			Progress = 0.8309352f;
			CSVBullet.Load();
			Progress = 0.8327338f;
			CSVBuff.Load();
			Progress = 0.8345324f;
			CSVBubble.Load();
			Progress = 0.836331f;
			CSVBraveTeamNews.Load();
			Progress = 0.8381295f;
			CSVBraveTeamMeetingCondition.Load();
			Progress = 0.839928f;
			CSVBraveTeamMeeting.Load();
			Progress = 0.8417266f;
			CSVBraveBiography.Load();
			Progress = 0.8435252f;
			CSVBrave.Load();
			Progress = 0.8453237f;
			CSVBoxType.Load();
			Progress = 0.8471223f;
			CSVBOSSTowerStage.Load();
			Progress = 0.8489209f;
			CSVBOSSTowerRankReward.Load();
			Progress = 0.8507195f;
			CSVBOSSTowerQualifier.Load();
			Progress = 0.852518f;
			CSVBOSSTowerParameter.Load();
			Progress = 0.8543165f;
			CSVBOSSTower.Load();
			Progress = 0.8561151f;
			CSVBOSSManual.Load();
			Progress = 0.8579137f;
			CSVBOSSInformation.Load();
			Progress = 0.8597122f;
			CSVBOOSFightPlayMode.Load();
			Progress = 0.8615108f;
			CSVBondEffect.Load();
			Progress = 0.8633093f;
			CSVBond.Load();
			Progress = 0.8651079f;
			CSVBlessTimes.Load();
			Progress = 0.8669065f;
			CSVBless.Load();
			Progress = 0.868705f;
			CSVBiographySeries.Load();
			Progress = 0.8705036f;
			CSVBattleType.Load();
			Progress = 0.8723022f;
			CSVBattleStage.Load();
			Progress = 0.8741007f;
			CSVBattleScene.Load();
			Progress = 0.8758993f;
			CSVBattleRules.Load();
			Progress = 0.8776978f;
			CSVBattleRuleDesc.Load();
			Progress = 0.8794964f;
			CSVBattlePet.Load();
			Progress = 0.881295f;
			CSVBattlePassUpgrade.Load();
			Progress = 0.8830935f;
			CSVBattlePassTaskGroup.Load();
			Progress = 0.8848921f;
			CSVBattlePassTask.Load();
			Progress = 0.8866907f;
			CSVBattlePassRewardDisplay.Load();
			Progress = 0.8884892f;
			CSVBattlePassPurchase.Load();
			Progress = 0.8902878f;
			CSVBattleMenuType.Load();
			Progress = 0.8920863f;
			CSVBattleMenuFunction.Load();
			Progress = 0.8938849f;
			CSVBattleEvent.Load();
			Progress = 0.8956835f;
			CSVBattleDrop.Load();
			Progress = 0.897482f;
			CSVBackgroundStory.Load();
			Progress = 0.8992805f;
			CSVAwardQualityEffect.Load();
			Progress = 0.9010791f;
			CSVAwardPreview.Load();
			Progress = 0.9028777f;
			CSVAward.Load();
			Progress = 0.9046763f;
			CSVAwakeningCondtion.Load();
			Progress = 0.9064748f;
			CSVAutoBattle.Load();
			Progress = 0.9082734f;
			CSVAttrConvert.Load();
			Progress = 0.910072f;
			CSVAttrBoost.Load();
			Progress = 0.9118705f;
			CSVAttr.Load();
			Progress = 0.913669f;
			CSVAssessType.Load();
			Progress = 0.9154676f;
			CSVAssessScore.Load();
			Progress = 0.9172662f;
			CSVAssessMain.Load();
			Progress = 0.9190648f;
			CSVArenaWinAward.Load();
			Progress = 0.9208633f;
			CSVArenaSegmentInformation.Load();
			Progress = 0.9226618f;
			CSVArenaRankingAward.Load();
			Progress = 0.9244604f;
			CSVArenaRandAward.Load();
			Progress = 0.926259f;
			CSVArenaMaxStars.Load();
			Progress = 0.9280576f;
			CSVArenaCumlativeRewards.Load();
			Progress = 0.9298561f;
			CSVArenaActNumperiods.Load();
			Progress = 0.9316547f;
			CSVAreaProtectionParameters.Load();
			Progress = 0.9334533f;
			CSVAreaProtection.Load();
			Progress = 0.9352518f;
			CSVAnnouncement.Load();	//depends: CSVWordStyle;
			Progress = 0.9370503f;
			CSVAllRaceBonus.Load();
			Progress = 0.9388489f;
			CSVAidValue.Load();
			Progress = 0.9406475f;
			CSVAidPoint.Load();
			Progress = 0.9424461f;
			CSVAICharacter.Load();
			Progress = 0.9442446f;
			CSVAiBubbleChat.Load();
			Progress = 0.9460432f;
			CSVAdventureProgress.Load();
			Progress = 0.9478417f;
			CSVAdventureMap.Load();
			Progress = 0.9496403f;
			CSVAdventureLevel.Load();
			Progress = 0.9514388f;
			CSVAdventureCriminal.Load();
			Progress = 0.9532374f;
			CSVActivityUiJump.Load();
			Progress = 0.955036f;
			CSVActivityTime.Load();
			Progress = 0.9568346f;
			CSVActivityTarget.Load();
			Progress = 0.9586331f;
			CSVActivityShopGoods.Load();
			Progress = 0.9604316f;
			CSVActivityShop.Load();
			Progress = 0.9622302f;
			CSVActivityQuestGroup.Load();
			Progress = 0.9640288f;
			CSVActivityMainUi.Load();
			Progress = 0.9658273f;
			CSVActivityMainnUi.Load();
			Progress = 0.9676259f;
			CSVActiveSkillShowId.Load();
			Progress = 0.9694245f;
			CSVActiveSkillShow.Load();
			Progress = 0.971223f;
			CSVActiveSkillInfo.Load();
			Progress = 0.9730216f;
			CSVActiveSkillEffective.Load();
			Progress = 0.9748201f;
			CSVActiveSkillBehavior.Load();
			Progress = 0.9766187f;
			CSVActiveSkill.Load();
			Progress = 0.9784173f;
			CSVActiverEmergencySwitch.Load();
			Progress = 0.9802158f;
			CSVActionState.Load();
			Progress = 0.9820144f;
			CSVAction.Load();
			Progress = 0.9838129f;
			CSVAchievementType.Load();
			Progress = 0.9856115f;
			CSVAchievementLevel.Load();
			Progress = 0.9874101f;
			CSVAchievementLanguage.Load();
			Progress = 0.9892086f;
			CSVAchievementIconMix.Load();
			Progress = 0.9910072f;
			CSVAchievementDrop.Load();
			Progress = 0.9928058f;
			CSVAchievement.Load();
			Progress = 0.9946043f;
			CSVAccruePay.Load();
			Progress = 0.9964029f;
			CSVAccrueConsume.Load();
			Progress = 0.9982014f;
			CSBiographyChapter.Load();
			Progress = 1f;

			isFinished = true;
		}
		public static void Unload()
		{
			Progress = 0f;
			isFinished = false;
			CSVWordStyle.Unload();
			CSVLanguage.Unload();
			CSVTaskLanguage.Unload();
			CSVWorldLevel.Unload();
			CSVWelfareType.Unload();
			CSVWelfareMenu.Unload();
			CSVWeatherTime.Unload();
			CSVWeatherSpecial.Unload();
			CSVWeatherSeason.Unload();
			CSVWeather.Unload();
			CSVVitality.Unload();
			CSVVideoType.Unload();
			CSVUplifted.Unload();
			CSVUpgradeEffect.Unload();
			CSVUnlock.Unload();
			CSVUIRule.Unload();
			CSVUiRelation.Unload();
			CSVTutorialSecondHeading.Unload();
			CSVTutorialFirstHeading.Unload();
			CSVTutorialDetails.Unload();
			CSVTutorial.Unload();
			CSVTutor.Unload();
			CSVTtArenaWinAward.Unload();
			CSVTtArenaSegmentInformation.Unload();
			CSVTtArenaRankingAward.Unload();
			CSVTtArenaRandAward.Unload();
			CSVTtArenaMaxStars.Unload();
			CSVTtArenaCumlativeRewards.Unload();
			CSVTrialStage.Unload();
			CSVTrialSkillBar.Unload();
			CSVTrialPreSkill.Unload();
			CSVTrialParameters.Unload();
			CSVTrialLevelGrade.Unload();
			CSVTrialCharacteristic.Unload();
			CSVTrialBadge.Unload();
			CSVTreasuresUnlock.Unload();
			CSVTreasuresLevel.Unload();
			CSVTreasures.Unload();
			CSVTreasureRaider.Unload();
			CSVTravellerAwakening.Unload();
			CSVTransform.Unload();
			CSVTradeParam.Unload();
			CSVTrade.Unload();
			CSVTrack.Unload();
			CSVTownType.Unload();
			CSVTownTaskLibrary.Unload();
			CSVTownTask.Unload();
			CSVTownContributeLv.Unload();
			CSVTownContributeAward.Unload();
			CSVTitleSeries.Unload();
			CSVTitleColumn.Unload();
			CSVTitle.Unload();
			CSVTipsLvl.Unload();
			CSVTips.Unload();
			CSVTianTiWinAward.Unload();
			CSVTianTiTask.Unload();
			CSVTianTiSegmentInformation.Unload();
			CSVTianTiRankingAward.Unload();
			CSVTianTiCumlativeRewards.Unload();
			CSVTerrorSeriesData.Unload();
			CSVTerrorSeries.Unload();
			CSVTemporary.Unload();
			CSVTeamTarget.Unload();
			CSVTeamLogo.Unload();
			CSVTeam.Unload();
			CSVTeaching.Unload();
			CSVTaskPage.Unload();
			CSVTaskLevelConfine.Unload();
			CSVTaskGoal.Unload();
			CSVTaskCategory.Unload();
			CSVTask.Unload();
			CSVTalkChoose.Unload();
			CSVTalentExchange.Unload();
			CSVTalent.Unload();
			CSVSystemEffect.Unload();
			CSVSynthesis.Unload();
			CSVSwitchCondition.Unload();
			CSVSurvivalRankReward.Unload();
			CSVSurvivalHangupReward.Unload();
			CSVSurvivalFightReward.Unload();
			CSVSuitEffect.Unload();
			CSVSuit.Unload();
			CSVSubtitle.Unload();
			CSVSubmitPetCondition.Unload();
			CSVSubmit.Unload();
			CSVStoneStage.Unload();
			CSVStoneLevel.Unload();
			CSVStone.Unload();
			CSVStatus.Unload();
			CSVStageReward.Unload();
			CSVSpecialGoldPetExchange.Unload();
			CSVSpecialGoldPetAppointExchange.Unload();
			CSVSound.Unload();
			CSVSoulBeadUnlock.Unload();
			CSVSoulBeadSkill.Unload();
			CSVSoulBeadPetAddexp.Unload();
			CSVSoulBead.Unload();
			CSVSlotUpgrade.Unload();
			CSVSkillSE.Unload();
			CSVSinglePay.Unload();
			CSVSigninRewardModel.Unload();
			CSVSigninReward.Unload();
			CSVSignActivity.Unload();
			CSVSign.Unload();
			CSVShopItem.Unload();
			CSVShop.Unload();
			CSVShock.Unload();
			CSVSEState.Unload();
			CSVSeekItem.Unload();
			CSVSceneNubber.Unload();
			CSVSavingsBank.Unload();
			CSVRuneTypeID.Unload();
			CSVRuneSynthetise.Unload();
			CSVRuneSlot.Unload();
			CSVRuneLvlID.Unload();
			CSVRuneInfo.Unload();
			CSVRule.Unload();
			CSVRobotName.Unload();
			CSVRobotList.Unload();
			CSVRobotAttr.Unload();
			CSVReturnSign.Unload();
			CSVReturnShop.Unload();
			CSVReturnRecover.Unload();
			CSVReturnParam.Unload();
			CSVReturnMenu.Unload();
			CSVReturnGifts.Unload();
			CSVReturnCommodity.Unload();
			CSVReturnChanllengeTask.Unload();
			CSVReturnChanllengeIntegral.Unload();
			CSVReturnArdentReward.Unload();
			CSVReturnArdent.Unload();
			CSVResolving.Unload();
			CSVRedEnvelopRain.Unload();
			CSVRechargeSelection.Unload();
			CSVRebuildExpend.Unload();
			CSVRanklistsort.Unload();
			CSVRanklistset.Unload();
			CSVRanklistmain.Unload();
			CSVRandomSkillLibrary.Unload();
			CSVRaceSkillType.Unload();
			CSVRaceDepartmentResearch.Unload();
			CSVRaceChangeSkill.Unload();
			CSVRaceChangeResearch.Unload();
			CSVRaceChangeGroup.Unload();
			CSVRaceChangeCard.Unload();
			CSVQuestionnaire.Unload();
			CSVQuestDailyControl.Unload();
			CSVQualityParameter.Unload();
			CSVPublicityMap.Unload();
			CSVPromptBox.Unload();
			CSVPromoteCareer.Unload();
			CSVPrivilege.Unload();
			CSVPositionPoint.Unload();
			CSVPKMatch.Unload();
			CSVPetRemake.Unload();
			CSVPetRelease.Unload();
			CSVPetNewTemplate.Unload();
			CSVPetNewSkillSummary.Unload();
			CSVPetNewSkillSort.Unload();
			CSVPetNewSkillsLv.Unload();
			CSVPetNewShowFilter.Unload();
			CSVPetNewSeal.Unload();
			CSVPetNewReBuild.Unload();
			CSVPetNewParam.Unload();
			CSVPetNewMapRarity.Unload();
			CSVPetNewlv.Unload();
			CSVPetNewLoyaty.Unload();
			CSVPetNewLoveUp.Unload();
			CSVPetNewIsMount.Unload();
			CSVPetNewExchange.Unload();
			CSVPetNewEnhance.Unload();
			CSVPetNewAreaControl.Unload();
			CSVPetNew.Unload();
			CSVPetMountStrengthen.Unload();
			CSVPetMountAttr.Unload();
			CSVPetMount.Unload();
			CSVPetFashion.Unload();
			CSVPetexploreTaskGroup.Unload();
			CSVPetexploreReward.Unload();
			CSVPetEquipSuitSkill.Unload();
			CSVPetEquipSuitAppearance.Unload();
			CSVPetEquipQualityParameter.Unload();
			CSVPetEquipQuality.Unload();
			CSVPetEquipEffect.Unload();
			CSVPetEquipAttr.Unload();
			CSVPetEquip.Unload();
			CSVPetBank.Unload();
			CSVPedigreedTaskGroup.Unload();
			CSVPedigreedParameter.Unload();
			CSVPedigreedDraw.Unload();
			CSVPassiveSkillInfo.Unload();
			CSVPassiveSkill.Unload();
			CSVPartnerSkill.Unload();
			CSVPartnerQuality.Unload();
			CSVPartnerOccupation.Unload();
			CSVPartnerLevel.Unload();
			CSVPartnerBelonging.Unload();
			CSVPartner.Unload();
			CSVParam.Unload();
			CSVOrnamentsUpgrade.Unload();
			CSVOrnamentsType.Unload();
			CSVOrnamentsSkill.Unload();
			CSVOrnamentsAttributes.Unload();
			CSVOperationalActivityRuler.Unload();
			CSVOperatereward.Unload();
			CSVOpenUi.Unload();
			CSVOneCoinLottey.Unload();
			CSVNubber.Unload();
			CSVNpcPathFinding.Unload();
			CSVNPCOccupation.Unload();
			CSVNPCMood.Unload();
			CSVNpcLanguage.Unload();
			CSVNPCHealth.Unload();
			CSVNPCHead.Unload();
			CSVNpcFunctionData.Unload();
			CSVNPCFavorabilityStage.Unload();
			CSVNPCFavorability.Unload();
			CSVNPCDisease.Unload();
			CSVNPCCharacter.Unload();
			CSVNpc.Unload();
			CSVNien_Presonal_Rank.Unload();
			CSVNien_Parameters.Unload();
			CSVNien_Enemy_Gropu.Unload();
			CSVNien_Damage_Accumulate.Unload();
			CSVNienPresonalRank.Unload();
			CSVNienParameters.Unload();
			CSVNienEnemyGropu.Unload();
			CSVNienDamageAccumulate.Unload();
			CSVNewBiographySeries.Unload();
			CSVNaviMap.Unload();
			CSVMoodSymbol.Unload();
			CSVMonthCard.Unload();
			CSVMonsterPvp.Unload();
			CSVMonsterAttribute.Unload();
			CSVMonster.Unload();
			CSVMoneyShow.Unload();
			CSVMoliSpirit.Unload();
			CSVMerchantFleetTask.Unload();
			CSVMerchantFleetLevel.Unload();
			CSVMemoryPieces.Unload();
			CSVMatch.Unload();
			CSVMapInfo.Unload();
			CSVMapExplorationReward.Unload();
			CSVMapExplorationMark.Unload();
			CSVMapBitsInfo.Unload();
			CSVMall.Unload();
			CSVMail.Unload();
			CSVLossTipsBanList.Unload();
			CSVLittleGame_OneTOuchDraw.Unload();
			CSVLittleGame_Elimination.Unload();
			CSVLifeSkillRank.Unload();
			CSVLifeSkillLevel.Unload();
			CSVLifeSkill.Unload();
			CSVLevelName.Unload();
			CSVLevelGift.Unload();
			CSVJewelRecommend.Unload();
			CSVJewel.Unload();
			CSVItemSource.Unload();
			CSVItemFun.Unload();
			CSVItem.Unload();
			CSVIsland.Unload();
			CSVInterfaceBubble.Unload();
			CSVInteractivePerform.Unload();
			CSVInstanceParam.Unload();
			CSVInstanceDaily.Unload();
			CSVInstance.Unload();
			CSVIndustryTask.Unload();
			CSVIndustryActivity.Unload();
			CSVImprintUpgrade.Unload();
			CSVImprintNode.Unload();
			CSVImprintLabel.Unload();
			CSVIDIP.Unload();
			CSVIconConfigure.Unload();
			CSVHundredChapter.Unload();
			CSVHotKey.Unload();
			CSVHorn.Unload();
			CSVHeadframe.Unload();
			CSVHead.Unload();
			CSVHangupParam.Unload();
			CSVHangupLayerStage.Unload();
			CSVHangup.Unload();
			CSVGuideTip.Unload();
			CSVGuideModel.Unload();
			CSVGuideGroup.Unload();
			CSVGuideEffect.Unload();
			CSVGuideCondition.Unload();
			CSVGuideArrow.Unload();
			CSVGuide.Unload();
			CSVGrowthFund.Unload();
			CSVGreen.Unload();
			CSVGoldPetExchange.Unload();
			CSVGoddessTopic.Unload();
			CSVGoddessSelect.Unload();
			CSVGoddessGift.Unload();
			CSVGoddessEnd.Unload();
			CSVGMMail.Unload();
			CSVGleanings.Unload();
			CSVGenus.Unload();
			CSVFunForeshow.Unload();
			CSVFunctionOpen.Unload();
			CSVFunctionGroup.Unload();
			CSVFunction.Unload();
			CSVFriendSendItem.Unload();
			CSVFriendSearch.Unload();
			CSVFriendIntimacy.Unload();
			CSVFormulaSelect.Unload();
			CSVFormulaParam.Unload();
			CSVFormula.Unload();
			CSVFoodIsShow.Unload();
			CSVFoodAtlas.Unload();
			CSVFirstCharge.Unload();
			CSVFestivalTask.Unload();
			CSVFavorabilityStamina.Unload();
			CSVFavorabilityStageName.Unload();
			CSVFavorabilityPlaceReward.Unload();
			CSVFavorabilityGiftType.Unload();
			CSVFavorabilityGift.Unload();
			CSVFavorabilityBehavior.Unload();
			CSVFavorabilityBanquet.Unload();
			CSVFashionWeaponModel.Unload();
			CSVFashionWeapon.Unload();
			CSVFashionSuit.Unload();
			CSVFashionScroe.Unload();
			CSVFashionModel.Unload();
			CSVFashionIcon.Unload();
			CSVFashionDraw.Unload();
			CSVFashionColour.Unload();
			CSVFashionClothes.Unload();
			CSVFashionAttr.Unload();
			CSVFashionActivity.Unload();
			CSVFashionAccessory.Unload();
			CSVFamilySkillUp.Unload();
			CSVFamilyResBattleTeam.Unload();
			CSVFamilyResBattleState.Unload();
			CSVFamilyResBattleResult.Unload();
			CSVFamilyResBattleResParameter.Unload();
			CSVFamilyResBattleParameter.Unload();
			CSVFamilyResBattleCombatParameter.Unload();
			CSVFamilyResBattleCamp.Unload();
			CSVFamilyReception.Unload();
			CSVFamilyProsperity.Unload();
			CSVFamilyProhibitionMerger.Unload();
			CSVFamilyPostAuthority.Unload();
			CSVFamilyPetType.Unload();
			CSVFamilyPetTrainingStarReward.Unload();
			CSVFamilyPetTrainingRankReward.Unload();
			CSVFamilyPetMood.Unload();
			CSVFamilyPetHealth.Unload();
			CSVFamilyPetFood.Unload();
			CSVFamilyPet.Unload();
			CSVFamilyPacketSection.Unload();
			CSVFamilyPacketLimit.Unload();
			CSVFamilyPacket.Unload();
			CSVFamilyItem.Unload();
			CSVFamilyFight.Unload();
			CSVFamilyDonateTime.Unload();
			CSVFamilyDonate.Unload();
			CSVFamilyBossRankReward.Unload();
			CSVFamilyBossParam.Unload();
			CSVFamilyBossFamilyReward.Unload();
			CSVFamilyBonus.Unload();
			CSVFamilyAuctionDrop.Unload();
			CSVFamilyAuctionAward.Unload();
			CSVFamilyAuctionAct.Unload();
			CSVFamilyAuction.Unload();
			CSVFamilyAthleticsWinAward.Unload();
			CSVFamilyAthleticsRankReset.Unload();
			CSVFamilyAthleticsRankAward.Unload();
			CSVFamilyAthleticsParameter.Unload();
			CSVFamilyAthleticsInspireBuff.Unload();
			CSVFamilyAthleticsInspireAward.Unload();
			CSVFamilyArchitectureEffect.Unload();
			CSVFamilyArchitecture.Unload();
			CSVFamilyActive.Unload();
			CSVFameRank.Unload();
			CSVFameAddition.Unload();
			CSVexpRetrieve.Unload();
			CSVExploringSkill.Unload();
			CSVExperienceLevel.Unload();
			CSVExperienceAttrRank.Unload();
			CSVExperienceAttr.Unload();
			CSVExchangeItem.Unload();
			CSVErrorCode.Unload();
			CSVEquipmentRebuild.Unload();
			CSVEquipmentParameter.Unload();
			CSVEquipmentEffect.Unload();
			CSVEquipment.Unload();
			CSVElementAttributes.Unload();
			CSVEffect.Unload();
			CSVEditorMap.Unload();
			CSVDynamicAttribute.Unload();
			CSVDubbing.Unload();
			CSVDrop.Unload();
			CSVDressUnlock.Unload();
			CSVDomesticationTask.Unload();
			CSVDomesticationRank.Unload();
			CSVDomesticationEffect.Unload();
			CSVDialogueLanguage.Unload();
			CSVDialogue.Unload();
			CSVDevice.Unload();
			CSVDetect.Unload();
			CSVDeliver.Unload();
			CSVDecisiveArenaRankingRedward.Unload();
			CSVDecisiveArenaParam.Unload();
			CSVDamageShowType.Unload();
			CSVDamageShowConfig.Unload();
			CSVDaliyPacks.Unload();
			CSVDailyActivityWeek.Unload();
			CSVDailyActivityShow.Unload();
			CSVDailyActivityReward.Unload();
			CSVDailyActivityPush.Unload();
			CSVDailyActivity.Unload();
			CSVCutSceneSubTitle.Unload();
			CSVCutScene.Unload();
			CSVCustomizeBag.Unload();
			CSVCumulativeReward.Unload();
			CSVCookLv.Unload();
			CSVCookFunction.Unload();
			CSVCookBookReward.Unload();
			CSVCookAttr.Unload();
			CSVCook.Unload();
			CSVConditionalGift.Unload();
			CSVComposeMenu.Unload();
			CSVCompose.Unload();
			CSVCommodityList.Unload();
			CSVCommodityCategory.Unload();
			CSVCommodity.Unload();
			CSVCommand.Unload();
			CSVCollectionProcess.Unload();
			CSVCollection.Unload();
			CSVCode.Unload();
			CSVClueTask.Unload();
			CSVCluePhasedTasksGroup.Unload();
			CSVClueDetectiveLevel.Unload();
			CSVClueAdventureLevel.Unload();
			CSVClassicBoss.Unload();
			CSVChronology.Unload();
			CSVChoseTargetLimit.Unload();
			CSVChoseSkillLimit.Unload();
			CSVCheckseq.Unload();
			CSVChatWord.Unload();
			CSVChatframe.Unload();
			CSVChatBlackIndustry.Unload();
			CSVChatBack.Unload();
			CSVChargeList.Unload();
			CSVCharacterWeapon.Unload();
			CSVCharacterHead.Unload();
			CSVCharacterAttribute.Unload();
			CSVCharacter.Unload();
			CSVChapterSysTask.Unload();
			CSVChapterInfo.Unload();
			CSVChapterFunctionList.Unload();
			CSVChapter.Unload();
			CSVChaosAttr.Unload();
			CSVChallengeLevel.Unload();
			CSVChallengeArenaRankAward.Unload();
			CSVChallengeArenaParameter.Unload();
			CSVCareerTeaching.Unload();
			CSVCareerChange.Unload();
			CSVCareer.Unload();
			CSVCaptainPoint.Unload();
			CSVCampInformation.Unload();
			CSVBullet.Unload();
			CSVBuff.Unload();
			CSVBubble.Unload();
			CSVBraveTeamNews.Unload();
			CSVBraveTeamMeetingCondition.Unload();
			CSVBraveTeamMeeting.Unload();
			CSVBraveBiography.Unload();
			CSVBrave.Unload();
			CSVBoxType.Unload();
			CSVBOSSTowerStage.Unload();
			CSVBOSSTowerRankReward.Unload();
			CSVBOSSTowerQualifier.Unload();
			CSVBOSSTowerParameter.Unload();
			CSVBOSSTower.Unload();
			CSVBOSSManual.Unload();
			CSVBOSSInformation.Unload();
			CSVBOOSFightPlayMode.Unload();
			CSVBondEffect.Unload();
			CSVBond.Unload();
			CSVBlessTimes.Unload();
			CSVBless.Unload();
			CSVBiographySeries.Unload();
			CSVBattleType.Unload();
			CSVBattleStage.Unload();
			CSVBattleScene.Unload();
			CSVBattleRules.Unload();
			CSVBattleRuleDesc.Unload();
			CSVBattlePet.Unload();
			CSVBattlePassUpgrade.Unload();
			CSVBattlePassTaskGroup.Unload();
			CSVBattlePassTask.Unload();
			CSVBattlePassRewardDisplay.Unload();
			CSVBattlePassPurchase.Unload();
			CSVBattleMenuType.Unload();
			CSVBattleMenuFunction.Unload();
			CSVBattleEvent.Unload();
			CSVBattleDrop.Unload();
			CSVBackgroundStory.Unload();
			CSVAwardQualityEffect.Unload();
			CSVAwardPreview.Unload();
			CSVAward.Unload();
			CSVAwakeningCondtion.Unload();
			CSVAutoBattle.Unload();
			CSVAttrConvert.Unload();
			CSVAttrBoost.Unload();
			CSVAttr.Unload();
			CSVAssessType.Unload();
			CSVAssessScore.Unload();
			CSVAssessMain.Unload();
			CSVArenaWinAward.Unload();
			CSVArenaSegmentInformation.Unload();
			CSVArenaRankingAward.Unload();
			CSVArenaRandAward.Unload();
			CSVArenaMaxStars.Unload();
			CSVArenaCumlativeRewards.Unload();
			CSVArenaActNumperiods.Unload();
			CSVAreaProtectionParameters.Unload();
			CSVAreaProtection.Unload();
			CSVAnnouncement.Unload();
			CSVAllRaceBonus.Unload();
			CSVAidValue.Unload();
			CSVAidPoint.Unload();
			CSVAICharacter.Unload();
			CSVAiBubbleChat.Unload();
			CSVAdventureProgress.Unload();
			CSVAdventureMap.Unload();
			CSVAdventureLevel.Unload();
			CSVAdventureCriminal.Unload();
			CSVActivityUiJump.Unload();
			CSVActivityTime.Unload();
			CSVActivityTarget.Unload();
			CSVActivityShopGoods.Unload();
			CSVActivityShop.Unload();
			CSVActivityQuestGroup.Unload();
			CSVActivityMainUi.Unload();
			CSVActivityMainnUi.Unload();
			CSVActiveSkillShowId.Unload();
			CSVActiveSkillShow.Unload();
			CSVActiveSkillInfo.Unload();
			CSVActiveSkillEffective.Unload();
			CSVActiveSkillBehavior.Unload();
			CSVActiveSkill.Unload();
			CSVActiverEmergencySwitch.Unload();
			CSVActionState.Unload();
			CSVAction.Unload();
			CSVAchievementType.Unload();
			CSVAchievementLevel.Unload();
			CSVAchievementLanguage.Unload();
			CSVAchievementIconMix.Unload();
			CSVAchievementDrop.Unload();
			CSVAchievement.Unload();
			CSVAccruePay.Unload();
			CSVAccrueConsume.Unload();
			CSBiographyChapter.Unload();

		}
		public static List<string> GetAllFiles()
		{
			List<string> paths = new List<string>(556);
			paths.Add("Config/Table/CSVWordStyle.bytes");
			paths.Add("Config/Table/CSVLanguage.bytes");
			paths.Add("Config/Table/CSVTaskLanguage.bytes");
			paths.Add("Config/Table/CSVWorldLevel.bytes");
			paths.Add("Config/Table/CSVWelfareType.bytes");
			paths.Add("Config/Table/CSVWelfareMenu.bytes");
			paths.Add("Config/Table/CSVWeatherTime.bytes");
			paths.Add("Config/Table/CSVWeatherSpecial.bytes");
			paths.Add("Config/Table/CSVWeatherSeason.bytes");
			paths.Add("Config/Table/CSVWeather.bytes");
			paths.Add("Config/Table/CSVVitality.bytes");
			paths.Add("Config/Table/CSVVideoType.bytes");
			paths.Add("Config/Table/CSVUplifted.bytes");
			paths.Add("Config/Table/CSVUpgradeEffect.bytes");
			paths.Add("Config/Table/CSVUnlock.bytes");
			paths.Add("Config/Table/CSVUIRule.bytes");
			paths.Add("Config/Table/CSVUiRelation.bytes");
			paths.Add("Config/Table/CSVTutorialSecondHeading.bytes");
			paths.Add("Config/Table/CSVTutorialFirstHeading.bytes");
			paths.Add("Config/Table/CSVTutorialDetails.bytes");
			paths.Add("Config/Table/CSVTutorial.bytes");
			paths.Add("Config/Table/CSVTutor.bytes");
			paths.Add("Config/Table/CSVTtArenaWinAward.bytes");
			paths.Add("Config/Table/CSVTtArenaSegmentInformation.bytes");
			paths.Add("Config/Table/CSVTtArenaRankingAward.bytes");
			paths.Add("Config/Table/CSVTtArenaRandAward.bytes");
			paths.Add("Config/Table/CSVTtArenaMaxStars.bytes");
			paths.Add("Config/Table/CSVTtArenaCumlativeRewards.bytes");
			paths.Add("Config/Table/CSVTrialStage.bytes");
			paths.Add("Config/Table/CSVTrialSkillBar.bytes");
			paths.Add("Config/Table/CSVTrialPreSkill.bytes");
			paths.Add("Config/Table/CSVTrialParameters.bytes");
			paths.Add("Config/Table/CSVTrialLevelGrade.bytes");
			paths.Add("Config/Table/CSVTrialCharacteristic.bytes");
			paths.Add("Config/Table/CSVTrialBadge.bytes");
			paths.Add("Config/Table/CSVTreasuresUnlock.bytes");
			paths.Add("Config/Table/CSVTreasuresLevel.bytes");
			paths.Add("Config/Table/CSVTreasures.bytes");
			paths.Add("Config/Table/CSVTreasureRaider.bytes");
			paths.Add("Config/Table/CSVTravellerAwakening.bytes");
			paths.Add("Config/Table/CSVTransform.bytes");
			paths.Add("Config/Table/CSVTradeParam.bytes");
			paths.Add("Config/Table/CSVTrade.bytes");
			paths.Add("Config/Table/CSVTrack.bytes");
			paths.Add("Config/Table/CSVTownType.bytes");
			paths.Add("Config/Table/CSVTownTaskLibrary.bytes");
			paths.Add("Config/Table/CSVTownTask.bytes");
			paths.Add("Config/Table/CSVTownContributeLv.bytes");
			paths.Add("Config/Table/CSVTownContributeAward.bytes");
			paths.Add("Config/Table/CSVTitleSeries.bytes");
			paths.Add("Config/Table/CSVTitleColumn.bytes");
			paths.Add("Config/Table/CSVTitle.bytes");
			paths.Add("Config/Table/CSVTipsLvl.bytes");
			paths.Add("Config/Table/CSVTips.bytes");
			paths.Add("Config/Table/CSVTianTiWinAward.bytes");
			paths.Add("Config/Table/CSVTianTiTask.bytes");
			paths.Add("Config/Table/CSVTianTiSegmentInformation.bytes");
			paths.Add("Config/Table/CSVTianTiRankingAward.bytes");
			paths.Add("Config/Table/CSVTianTiCumlativeRewards.bytes");
			paths.Add("Config/Table/CSVTerrorSeriesData.bytes");
			paths.Add("Config/Table/CSVTerrorSeries.bytes");
			paths.Add("Config/Table/CSVTemporary.bytes");
			paths.Add("Config/Table/CSVTeamTarget.bytes");
			paths.Add("Config/Table/CSVTeamLogo.bytes");
			paths.Add("Config/Table/CSVTeam.bytes");
			paths.Add("Config/Table/CSVTeaching.bytes");
			paths.Add("Config/Table/CSVTaskPage.bytes");
			paths.Add("Config/Table/CSVTaskLevelConfine.bytes");
			paths.Add("Config/Table/CSVTaskGoal.bytes");
			paths.Add("Config/Table/CSVTaskCategory.bytes");
			paths.Add("Config/Table/CSVTask.bytes");
			paths.Add("Config/Table/CSVTalkChoose.bytes");
			paths.Add("Config/Table/CSVTalentExchange.bytes");
			paths.Add("Config/Table/CSVTalent.bytes");
			paths.Add("Config/Table/CSVSystemEffect.bytes");
			paths.Add("Config/Table/CSVSynthesis.bytes");
			paths.Add("Config/Table/CSVSwitchCondition.bytes");
			paths.Add("Config/Table/CSVSurvivalRankReward.bytes");
			paths.Add("Config/Table/CSVSurvivalHangupReward.bytes");
			paths.Add("Config/Table/CSVSurvivalFightReward.bytes");
			paths.Add("Config/Table/CSVSuitEffect.bytes");
			paths.Add("Config/Table/CSVSuit.bytes");
			paths.Add("Config/Table/CSVSubtitle.bytes");
			paths.Add("Config/Table/CSVSubmitPetCondition.bytes");
			paths.Add("Config/Table/CSVSubmit.bytes");
			paths.Add("Config/Table/CSVStoneStage.bytes");
			paths.Add("Config/Table/CSVStoneLevel.bytes");
			paths.Add("Config/Table/CSVStone.bytes");
			paths.Add("Config/Table/CSVStatus.bytes");
			paths.Add("Config/Table/CSVStageReward.bytes");
			paths.Add("Config/Table/CSVSpecialGoldPetExchange.bytes");
			paths.Add("Config/Table/CSVSpecialGoldPetAppointExchange.bytes");
			paths.Add("Config/Table/CSVSound.bytes");
			paths.Add("Config/Table/CSVSoulBeadUnlock.bytes");
			paths.Add("Config/Table/CSVSoulBeadSkill.bytes");
			paths.Add("Config/Table/CSVSoulBeadPetAddexp.bytes");
			paths.Add("Config/Table/CSVSoulBead.bytes");
			paths.Add("Config/Table/CSVSlotUpgrade.bytes");
			paths.Add("Config/Table/CSVSkillSE.bytes");
			paths.Add("Config/Table/CSVSinglePay.bytes");
			paths.Add("Config/Table/CSVSigninRewardModel.bytes");
			paths.Add("Config/Table/CSVSigninReward.bytes");
			paths.Add("Config/Table/CSVSignActivity.bytes");
			paths.Add("Config/Table/CSVSign.bytes");
			paths.Add("Config/Table/CSVShopItem.bytes");
			paths.Add("Config/Table/CSVShop.bytes");
			paths.Add("Config/Table/CSVShock.bytes");
			paths.Add("Config/Table/CSVSEState.bytes");
			paths.Add("Config/Table/CSVSeekItem.bytes");
			paths.Add("Config/Table/CSVSceneNubber.bytes");
			paths.Add("Config/Table/CSVSavingsBank.bytes");
			paths.Add("Config/Table/CSVRuneTypeID.bytes");
			paths.Add("Config/Table/CSVRuneSynthetise.bytes");
			paths.Add("Config/Table/CSVRuneSlot.bytes");
			paths.Add("Config/Table/CSVRuneLvlID.bytes");
			paths.Add("Config/Table/CSVRuneInfo.bytes");
			paths.Add("Config/Table/CSVRule.bytes");
			paths.Add("Config/Table/CSVRobotName.bytes");
			paths.Add("Config/Table/CSVRobotList.bytes");
			paths.Add("Config/Table/CSVRobotAttr.bytes");
			paths.Add("Config/Table/CSVReturnSign.bytes");
			paths.Add("Config/Table/CSVReturnShop.bytes");
			paths.Add("Config/Table/CSVReturnRecover.bytes");
			paths.Add("Config/Table/CSVReturnParam.bytes");
			paths.Add("Config/Table/CSVReturnMenu.bytes");
			paths.Add("Config/Table/CSVReturnGifts.bytes");
			paths.Add("Config/Table/CSVReturnCommodity.bytes");
			paths.Add("Config/Table/CSVReturnChanllengeTask.bytes");
			paths.Add("Config/Table/CSVReturnChanllengeIntegral.bytes");
			paths.Add("Config/Table/CSVReturnArdentReward.bytes");
			paths.Add("Config/Table/CSVReturnArdent.bytes");
			paths.Add("Config/Table/CSVResolving.bytes");
			paths.Add("Config/Table/CSVRedEnvelopRain.bytes");
			paths.Add("Config/Table/CSVRechargeSelection.bytes");
			paths.Add("Config/Table/CSVRebuildExpend.bytes");
			paths.Add("Config/Table/CSVRanklistsort.bytes");
			paths.Add("Config/Table/CSVRanklistset.bytes");
			paths.Add("Config/Table/CSVRanklistmain.bytes");
			paths.Add("Config/Table/CSVRandomSkillLibrary.bytes");
			paths.Add("Config/Table/CSVRaceSkillType.bytes");
			paths.Add("Config/Table/CSVRaceDepartmentResearch.bytes");
			paths.Add("Config/Table/CSVRaceChangeSkill.bytes");
			paths.Add("Config/Table/CSVRaceChangeResearch.bytes");
			paths.Add("Config/Table/CSVRaceChangeGroup.bytes");
			paths.Add("Config/Table/CSVRaceChangeCard.bytes");
			paths.Add("Config/Table/CSVQuestionnaire.bytes");
			paths.Add("Config/Table/CSVQuestDailyControl.bytes");
			paths.Add("Config/Table/CSVQualityParameter.bytes");
			paths.Add("Config/Table/CSVPublicityMap.bytes");
			paths.Add("Config/Table/CSVPromptBox.bytes");
			paths.Add("Config/Table/CSVPromoteCareer.bytes");
			paths.Add("Config/Table/CSVPrivilege.bytes");
			paths.Add("Config/Table/CSVPositionPoint.bytes");
			paths.Add("Config/Table/CSVPKMatch.bytes");
			paths.Add("Config/Table/CSVPetRemake.bytes");
			paths.Add("Config/Table/CSVPetRelease.bytes");
			paths.Add("Config/Table/CSVPetNewTemplate.bytes");
			paths.Add("Config/Table/CSVPetNewSkillSummary.bytes");
			paths.Add("Config/Table/CSVPetNewSkillSort.bytes");
			paths.Add("Config/Table/CSVPetNewSkillsLv.bytes");
			paths.Add("Config/Table/CSVPetNewShowFilter.bytes");
			paths.Add("Config/Table/CSVPetNewSeal.bytes");
			paths.Add("Config/Table/CSVPetNewReBuild.bytes");
			paths.Add("Config/Table/CSVPetNewParam.bytes");
			paths.Add("Config/Table/CSVPetNewMapRarity.bytes");
			paths.Add("Config/Table/CSVPetNewlv.bytes");
			paths.Add("Config/Table/CSVPetNewLoyaty.bytes");
			paths.Add("Config/Table/CSVPetNewLoveUp.bytes");
			paths.Add("Config/Table/CSVPetNewIsMount.bytes");
			paths.Add("Config/Table/CSVPetNewExchange.bytes");
			paths.Add("Config/Table/CSVPetNewEnhance.bytes");
			paths.Add("Config/Table/CSVPetNewAreaControl.bytes");
			paths.Add("Config/Table/CSVPetNew.bytes");
			paths.Add("Config/Table/CSVPetMountStrengthen.bytes");
			paths.Add("Config/Table/CSVPetMountAttr.bytes");
			paths.Add("Config/Table/CSVPetMount.bytes");
			paths.Add("Config/Table/CSVPetFashion.bytes");
			paths.Add("Config/Table/CSVPetexploreTaskGroup.bytes");
			paths.Add("Config/Table/CSVPetexploreReward.bytes");
			paths.Add("Config/Table/CSVPetEquipSuitSkill.bytes");
			paths.Add("Config/Table/CSVPetEquipSuitAppearance.bytes");
			paths.Add("Config/Table/CSVPetEquipQualityParameter.bytes");
			paths.Add("Config/Table/CSVPetEquipQuality.bytes");
			paths.Add("Config/Table/CSVPetEquipEffect.bytes");
			paths.Add("Config/Table/CSVPetEquipAttr.bytes");
			paths.Add("Config/Table/CSVPetEquip.bytes");
			paths.Add("Config/Table/CSVPetBank.bytes");
			paths.Add("Config/Table/CSVPedigreedTaskGroup.bytes");
			paths.Add("Config/Table/CSVPedigreedParameter.bytes");
			paths.Add("Config/Table/CSVPedigreedDraw.bytes");
			paths.Add("Config/Table/CSVPassiveSkillInfo.bytes");
			paths.Add("Config/Table/CSVPassiveSkill.bytes");
			paths.Add("Config/Table/CSVPartnerSkill.bytes");
			paths.Add("Config/Table/CSVPartnerQuality.bytes");
			paths.Add("Config/Table/CSVPartnerOccupation.bytes");
			paths.Add("Config/Table/CSVPartnerLevel.bytes");
			paths.Add("Config/Table/CSVPartnerBelonging.bytes");
			paths.Add("Config/Table/CSVPartner.bytes");
			paths.Add("Config/Table/CSVParam.bytes");
			paths.Add("Config/Table/CSVOrnamentsUpgrade.bytes");
			paths.Add("Config/Table/CSVOrnamentsType.bytes");
			paths.Add("Config/Table/CSVOrnamentsSkill.bytes");
			paths.Add("Config/Table/CSVOrnamentsAttributes.bytes");
			paths.Add("Config/Table/CSVOperationalActivityRuler.bytes");
			paths.Add("Config/Table/CSVOperatereward.bytes");
			paths.Add("Config/Table/CSVOpenUi.bytes");
			paths.Add("Config/Table/CSVOneCoinLottey.bytes");
			paths.Add("Config/Table/CSVNubber.bytes");
			paths.Add("Config/Table/CSVNpcPathFinding.bytes");
			paths.Add("Config/Table/CSVNPCOccupation.bytes");
			paths.Add("Config/Table/CSVNPCMood.bytes");
			paths.Add("Config/Table/CSVNpcLanguage.bytes");
			paths.Add("Config/Table/CSVNPCHealth.bytes");
			paths.Add("Config/Table/CSVNPCHead.bytes");
			paths.Add("Config/Table/CSVNpcFunctionData.bytes");
			paths.Add("Config/Table/CSVNPCFavorabilityStage.bytes");
			paths.Add("Config/Table/CSVNPCFavorability.bytes");
			paths.Add("Config/Table/CSVNPCDisease.bytes");
			paths.Add("Config/Table/CSVNPCCharacter.bytes");
			paths.Add("Config/Table/CSVNpc.bytes");
			paths.Add("Config/Table/CSVNien_Presonal_Rank.bytes");
			paths.Add("Config/Table/CSVNien_Parameters.bytes");
			paths.Add("Config/Table/CSVNien_Enemy_Gropu.bytes");
			paths.Add("Config/Table/CSVNien_Damage_Accumulate.bytes");
			paths.Add("Config/Table/CSVNienPresonalRank.bytes");
			paths.Add("Config/Table/CSVNienParameters.bytes");
			paths.Add("Config/Table/CSVNienEnemyGropu.bytes");
			paths.Add("Config/Table/CSVNienDamageAccumulate.bytes");
			paths.Add("Config/Table/CSVNewBiographySeries.bytes");
			paths.Add("Config/Table/CSVNaviMap.bytes");
			paths.Add("Config/Table/CSVMoodSymbol.bytes");
			paths.Add("Config/Table/CSVMonthCard.bytes");
			paths.Add("Config/Table/CSVMonsterPvp.bytes");
			paths.Add("Config/Table/CSVMonsterAttribute.bytes");
			paths.Add("Config/Table/CSVMonster.bytes");
			paths.Add("Config/Table/CSVMoneyShow.bytes");
			paths.Add("Config/Table/CSVMoliSpirit.bytes");
			paths.Add("Config/Table/CSVMerchantFleetTask.bytes");
			paths.Add("Config/Table/CSVMerchantFleetLevel.bytes");
			paths.Add("Config/Table/CSVMemoryPieces.bytes");
			paths.Add("Config/Table/CSVMatch.bytes");
			paths.Add("Config/Table/CSVMapInfo.bytes");
			paths.Add("Config/Table/CSVMapExplorationReward.bytes");
			paths.Add("Config/Table/CSVMapExplorationMark.bytes");
			paths.Add("Config/Table/CSVMapBitsInfo.bytes");
			paths.Add("Config/Table/CSVMall.bytes");
			paths.Add("Config/Table/CSVMail.bytes");
			paths.Add("Config/Table/CSVLossTipsBanList.bytes");
			paths.Add("Config/Table/CSVLittleGame_OneTOuchDraw.bytes");
			paths.Add("Config/Table/CSVLittleGame_Elimination.bytes");
			paths.Add("Config/Table/CSVLifeSkillRank.bytes");
			paths.Add("Config/Table/CSVLifeSkillLevel.bytes");
			paths.Add("Config/Table/CSVLifeSkill.bytes");
			paths.Add("Config/Table/CSVLevelName.bytes");
			paths.Add("Config/Table/CSVLevelGift.bytes");
			paths.Add("Config/Table/CSVJewelRecommend.bytes");
			paths.Add("Config/Table/CSVJewel.bytes");
			paths.Add("Config/Table/CSVItemSource.bytes");
			paths.Add("Config/Table/CSVItemFun.bytes");
			paths.Add("Config/Table/CSVItem.bytes");
			paths.Add("Config/Table/CSVIsland.bytes");
			paths.Add("Config/Table/CSVInterfaceBubble.bytes");
			paths.Add("Config/Table/CSVInteractivePerform.bytes");
			paths.Add("Config/Table/CSVInstanceParam.bytes");
			paths.Add("Config/Table/CSVInstanceDaily.bytes");
			paths.Add("Config/Table/CSVInstance.bytes");
			paths.Add("Config/Table/CSVIndustryTask.bytes");
			paths.Add("Config/Table/CSVIndustryActivity.bytes");
			paths.Add("Config/Table/CSVImprintUpgrade.bytes");
			paths.Add("Config/Table/CSVImprintNode.bytes");
			paths.Add("Config/Table/CSVImprintLabel.bytes");
			paths.Add("Config/Table/CSVIDIP.bytes");
			paths.Add("Config/Table/CSVIconConfigure.bytes");
			paths.Add("Config/Table/CSVHundredChapter.bytes");
			paths.Add("Config/Table/CSVHotKey.bytes");
			paths.Add("Config/Table/CSVHorn.bytes");
			paths.Add("Config/Table/CSVHeadframe.bytes");
			paths.Add("Config/Table/CSVHead.bytes");
			paths.Add("Config/Table/CSVHangupParam.bytes");
			paths.Add("Config/Table/CSVHangupLayerStage.bytes");
			paths.Add("Config/Table/CSVHangup.bytes");
			paths.Add("Config/Table/CSVGuideTip.bytes");
			paths.Add("Config/Table/CSVGuideModel.bytes");
			paths.Add("Config/Table/CSVGuideGroup.bytes");
			paths.Add("Config/Table/CSVGuideEffect.bytes");
			paths.Add("Config/Table/CSVGuideCondition.bytes");
			paths.Add("Config/Table/CSVGuideArrow.bytes");
			paths.Add("Config/Table/CSVGuide.bytes");
			paths.Add("Config/Table/CSVGrowthFund.bytes");
			paths.Add("Config/Table/CSVGreen.bytes");
			paths.Add("Config/Table/CSVGoldPetExchange.bytes");
			paths.Add("Config/Table/CSVGoddessTopic.bytes");
			paths.Add("Config/Table/CSVGoddessSelect.bytes");
			paths.Add("Config/Table/CSVGoddessGift.bytes");
			paths.Add("Config/Table/CSVGoddessEnd.bytes");
			paths.Add("Config/Table/CSVGMMail.bytes");
			paths.Add("Config/Table/CSVGleanings.bytes");
			paths.Add("Config/Table/CSVGenus.bytes");
			paths.Add("Config/Table/CSVFunForeshow.bytes");
			paths.Add("Config/Table/CSVFunctionOpen.bytes");
			paths.Add("Config/Table/CSVFunctionGroup.bytes");
			paths.Add("Config/Table/CSVFunction.bytes");
			paths.Add("Config/Table/CSVFriendSendItem.bytes");
			paths.Add("Config/Table/CSVFriendSearch.bytes");
			paths.Add("Config/Table/CSVFriendIntimacy.bytes");
			paths.Add("Config/Table/CSVFormulaSelect.bytes");
			paths.Add("Config/Table/CSVFormulaParam.bytes");
			paths.Add("Config/Table/CSVFormula.bytes");
			paths.Add("Config/Table/CSVFoodIsShow.bytes");
			paths.Add("Config/Table/CSVFoodAtlas.bytes");
			paths.Add("Config/Table/CSVFirstCharge.bytes");
			paths.Add("Config/Table/CSVFestivalTask.bytes");
			paths.Add("Config/Table/CSVFavorabilityStamina.bytes");
			paths.Add("Config/Table/CSVFavorabilityStageName.bytes");
			paths.Add("Config/Table/CSVFavorabilityPlaceReward.bytes");
			paths.Add("Config/Table/CSVFavorabilityGiftType.bytes");
			paths.Add("Config/Table/CSVFavorabilityGift.bytes");
			paths.Add("Config/Table/CSVFavorabilityBehavior.bytes");
			paths.Add("Config/Table/CSVFavorabilityBanquet.bytes");
			paths.Add("Config/Table/CSVFashionWeaponModel.bytes");
			paths.Add("Config/Table/CSVFashionWeapon.bytes");
			paths.Add("Config/Table/CSVFashionSuit.bytes");
			paths.Add("Config/Table/CSVFashionScroe.bytes");
			paths.Add("Config/Table/CSVFashionModel.bytes");
			paths.Add("Config/Table/CSVFashionIcon.bytes");
			paths.Add("Config/Table/CSVFashionDraw.bytes");
			paths.Add("Config/Table/CSVFashionColour.bytes");
			paths.Add("Config/Table/CSVFashionClothes.bytes");
			paths.Add("Config/Table/CSVFashionAttr.bytes");
			paths.Add("Config/Table/CSVFashionActivity.bytes");
			paths.Add("Config/Table/CSVFashionAccessory.bytes");
			paths.Add("Config/Table/CSVFamilySkillUp.bytes");
			paths.Add("Config/Table/CSVFamilyResBattleTeam.bytes");
			paths.Add("Config/Table/CSVFamilyResBattleState.bytes");
			paths.Add("Config/Table/CSVFamilyResBattleResult.bytes");
			paths.Add("Config/Table/CSVFamilyResBattleResParameter.bytes");
			paths.Add("Config/Table/CSVFamilyResBattleParameter.bytes");
			paths.Add("Config/Table/CSVFamilyResBattleCombatParameter.bytes");
			paths.Add("Config/Table/CSVFamilyResBattleCamp.bytes");
			paths.Add("Config/Table/CSVFamilyReception.bytes");
			paths.Add("Config/Table/CSVFamilyProsperity.bytes");
			paths.Add("Config/Table/CSVFamilyProhibitionMerger.bytes");
			paths.Add("Config/Table/CSVFamilyPostAuthority.bytes");
			paths.Add("Config/Table/CSVFamilyPetType.bytes");
			paths.Add("Config/Table/CSVFamilyPetTrainingStarReward.bytes");
			paths.Add("Config/Table/CSVFamilyPetTrainingRankReward.bytes");
			paths.Add("Config/Table/CSVFamilyPetMood.bytes");
			paths.Add("Config/Table/CSVFamilyPetHealth.bytes");
			paths.Add("Config/Table/CSVFamilyPetFood.bytes");
			paths.Add("Config/Table/CSVFamilyPet.bytes");
			paths.Add("Config/Table/CSVFamilyPacketSection.bytes");
			paths.Add("Config/Table/CSVFamilyPacketLimit.bytes");
			paths.Add("Config/Table/CSVFamilyPacket.bytes");
			paths.Add("Config/Table/CSVFamilyItem.bytes");
			paths.Add("Config/Table/CSVFamilyFight.bytes");
			paths.Add("Config/Table/CSVFamilyDonateTime.bytes");
			paths.Add("Config/Table/CSVFamilyDonate.bytes");
			paths.Add("Config/Table/CSVFamilyBossRankReward.bytes");
			paths.Add("Config/Table/CSVFamilyBossParam.bytes");
			paths.Add("Config/Table/CSVFamilyBossFamilyReward.bytes");
			paths.Add("Config/Table/CSVFamilyBonus.bytes");
			paths.Add("Config/Table/CSVFamilyAuctionDrop.bytes");
			paths.Add("Config/Table/CSVFamilyAuctionAward.bytes");
			paths.Add("Config/Table/CSVFamilyAuctionAct.bytes");
			paths.Add("Config/Table/CSVFamilyAuction.bytes");
			paths.Add("Config/Table/CSVFamilyAthleticsWinAward.bytes");
			paths.Add("Config/Table/CSVFamilyAthleticsRankReset.bytes");
			paths.Add("Config/Table/CSVFamilyAthleticsRankAward.bytes");
			paths.Add("Config/Table/CSVFamilyAthleticsParameter.bytes");
			paths.Add("Config/Table/CSVFamilyAthleticsInspireBuff.bytes");
			paths.Add("Config/Table/CSVFamilyAthleticsInspireAward.bytes");
			paths.Add("Config/Table/CSVFamilyArchitectureEffect.bytes");
			paths.Add("Config/Table/CSVFamilyArchitecture.bytes");
			paths.Add("Config/Table/CSVFamilyActive.bytes");
			paths.Add("Config/Table/CSVFameRank.bytes");
			paths.Add("Config/Table/CSVFameAddition.bytes");
			paths.Add("Config/Table/CSVexpRetrieve.bytes");
			paths.Add("Config/Table/CSVExploringSkill.bytes");
			paths.Add("Config/Table/CSVExperienceLevel.bytes");
			paths.Add("Config/Table/CSVExperienceAttrRank.bytes");
			paths.Add("Config/Table/CSVExperienceAttr.bytes");
			paths.Add("Config/Table/CSVExchangeItem.bytes");
			paths.Add("Config/Table/CSVErrorCode.bytes");
			paths.Add("Config/Table/CSVEquipmentRebuild.bytes");
			paths.Add("Config/Table/CSVEquipmentParameter.bytes");
			paths.Add("Config/Table/CSVEquipmentEffect.bytes");
			paths.Add("Config/Table/CSVEquipment.bytes");
			paths.Add("Config/Table/CSVElementAttributes.bytes");
			paths.Add("Config/Table/CSVEffect.bytes");
			paths.Add("Config/Table/CSVEditorMap.bytes");
			paths.Add("Config/Table/CSVDynamicAttribute.bytes");
			paths.Add("Config/Table/CSVDubbing.bytes");
			paths.Add("Config/Table/CSVDrop.bytes");
			paths.Add("Config/Table/CSVDressUnlock.bytes");
			paths.Add("Config/Table/CSVDomesticationTask.bytes");
			paths.Add("Config/Table/CSVDomesticationRank.bytes");
			paths.Add("Config/Table/CSVDomesticationEffect.bytes");
			paths.Add("Config/Table/CSVDialogueLanguage.bytes");
			paths.Add("Config/Table/CSVDialogue.bytes");
			paths.Add("Config/Table/CSVDevice.bytes");
			paths.Add("Config/Table/CSVDetect.bytes");
			paths.Add("Config/Table/CSVDeliver.bytes");
			paths.Add("Config/Table/CSVDecisiveArenaRankingRedward.bytes");
			paths.Add("Config/Table/CSVDecisiveArenaParam.bytes");
			paths.Add("Config/Table/CSVDamageShowType.bytes");
			paths.Add("Config/Table/CSVDamageShowConfig.bytes");
			paths.Add("Config/Table/CSVDaliyPacks.bytes");
			paths.Add("Config/Table/CSVDailyActivityWeek.bytes");
			paths.Add("Config/Table/CSVDailyActivityShow.bytes");
			paths.Add("Config/Table/CSVDailyActivityReward.bytes");
			paths.Add("Config/Table/CSVDailyActivityPush.bytes");
			paths.Add("Config/Table/CSVDailyActivity.bytes");
			paths.Add("Config/Table/CSVCutSceneSubTitle.bytes");
			paths.Add("Config/Table/CSVCutScene.bytes");
			paths.Add("Config/Table/CSVCustomizeBag.bytes");
			paths.Add("Config/Table/CSVCumulativeReward.bytes");
			paths.Add("Config/Table/CSVCookLv.bytes");
			paths.Add("Config/Table/CSVCookFunction.bytes");
			paths.Add("Config/Table/CSVCookBookReward.bytes");
			paths.Add("Config/Table/CSVCookAttr.bytes");
			paths.Add("Config/Table/CSVCook.bytes");
			paths.Add("Config/Table/CSVConditionalGift.bytes");
			paths.Add("Config/Table/CSVComposeMenu.bytes");
			paths.Add("Config/Table/CSVCompose.bytes");
			paths.Add("Config/Table/CSVCommodityList.bytes");
			paths.Add("Config/Table/CSVCommodityCategory.bytes");
			paths.Add("Config/Table/CSVCommodity.bytes");
			paths.Add("Config/Table/CSVCommand.bytes");
			paths.Add("Config/Table/CSVCollectionProcess.bytes");
			paths.Add("Config/Table/CSVCollection.bytes");
			paths.Add("Config/Table/CSVCode.bytes");
			paths.Add("Config/Table/CSVClueTask.bytes");
			paths.Add("Config/Table/CSVCluePhasedTasksGroup.bytes");
			paths.Add("Config/Table/CSVClueDetectiveLevel.bytes");
			paths.Add("Config/Table/CSVClueAdventureLevel.bytes");
			paths.Add("Config/Table/CSVClassicBoss.bytes");
			paths.Add("Config/Table/CSVChronology.bytes");
			paths.Add("Config/Table/CSVChoseTargetLimit.bytes");
			paths.Add("Config/Table/CSVChoseSkillLimit.bytes");
			paths.Add("Config/Table/CSVCheckseq.bytes");
			paths.Add("Config/Table/CSVChatWord.bytes");
			paths.Add("Config/Table/CSVChatframe.bytes");
			paths.Add("Config/Table/CSVChatBlackIndustry.bytes");
			paths.Add("Config/Table/CSVChatBack.bytes");
			paths.Add("Config/Table/CSVChargeList.bytes");
			paths.Add("Config/Table/CSVCharacterWeapon.bytes");
			paths.Add("Config/Table/CSVCharacterHead.bytes");
			paths.Add("Config/Table/CSVCharacterAttribute.bytes");
			paths.Add("Config/Table/CSVCharacter.bytes");
			paths.Add("Config/Table/CSVChapterSysTask.bytes");
			paths.Add("Config/Table/CSVChapterInfo.bytes");
			paths.Add("Config/Table/CSVChapterFunctionList.bytes");
			paths.Add("Config/Table/CSVChapter.bytes");
			paths.Add("Config/Table/CSVChaosAttr.bytes");
			paths.Add("Config/Table/CSVChallengeLevel.bytes");
			paths.Add("Config/Table/CSVChallengeArenaRankAward.bytes");
			paths.Add("Config/Table/CSVChallengeArenaParameter.bytes");
			paths.Add("Config/Table/CSVCareerTeaching.bytes");
			paths.Add("Config/Table/CSVCareerChange.bytes");
			paths.Add("Config/Table/CSVCareer.bytes");
			paths.Add("Config/Table/CSVCaptainPoint.bytes");
			paths.Add("Config/Table/CSVCampInformation.bytes");
			paths.Add("Config/Table/CSVBullet.bytes");
			paths.Add("Config/Table/CSVBuff.bytes");
			paths.Add("Config/Table/CSVBubble.bytes");
			paths.Add("Config/Table/CSVBraveTeamNews.bytes");
			paths.Add("Config/Table/CSVBraveTeamMeetingCondition.bytes");
			paths.Add("Config/Table/CSVBraveTeamMeeting.bytes");
			paths.Add("Config/Table/CSVBraveBiography.bytes");
			paths.Add("Config/Table/CSVBrave.bytes");
			paths.Add("Config/Table/CSVBoxType.bytes");
			paths.Add("Config/Table/CSVBOSSTowerStage.bytes");
			paths.Add("Config/Table/CSVBOSSTowerRankReward.bytes");
			paths.Add("Config/Table/CSVBOSSTowerQualifier.bytes");
			paths.Add("Config/Table/CSVBOSSTowerParameter.bytes");
			paths.Add("Config/Table/CSVBOSSTower.bytes");
			paths.Add("Config/Table/CSVBOSSManual.bytes");
			paths.Add("Config/Table/CSVBOSSInformation.bytes");
			paths.Add("Config/Table/CSVBOOSFightPlayMode.bytes");
			paths.Add("Config/Table/CSVBondEffect.bytes");
			paths.Add("Config/Table/CSVBond.bytes");
			paths.Add("Config/Table/CSVBlessTimes.bytes");
			paths.Add("Config/Table/CSVBless.bytes");
			paths.Add("Config/Table/CSVBiographySeries.bytes");
			paths.Add("Config/Table/CSVBattleType.bytes");
			paths.Add("Config/Table/CSVBattleStage.bytes");
			paths.Add("Config/Table/CSVBattleScene.bytes");
			paths.Add("Config/Table/CSVBattleRules.bytes");
			paths.Add("Config/Table/CSVBattleRuleDesc.bytes");
			paths.Add("Config/Table/CSVBattlePet.bytes");
			paths.Add("Config/Table/CSVBattlePassUpgrade.bytes");
			paths.Add("Config/Table/CSVBattlePassTaskGroup.bytes");
			paths.Add("Config/Table/CSVBattlePassTask.bytes");
			paths.Add("Config/Table/CSVBattlePassRewardDisplay.bytes");
			paths.Add("Config/Table/CSVBattlePassPurchase.bytes");
			paths.Add("Config/Table/CSVBattleMenuType.bytes");
			paths.Add("Config/Table/CSVBattleMenuFunction.bytes");
			paths.Add("Config/Table/CSVBattleEvent.bytes");
			paths.Add("Config/Table/CSVBattleDrop.bytes");
			paths.Add("Config/Table/CSVBackgroundStory.bytes");
			paths.Add("Config/Table/CSVAwardQualityEffect.bytes");
			paths.Add("Config/Table/CSVAwardPreview.bytes");
			paths.Add("Config/Table/CSVAward.bytes");
			paths.Add("Config/Table/CSVAwakeningCondtion.bytes");
			paths.Add("Config/Table/CSVAutoBattle.bytes");
			paths.Add("Config/Table/CSVAttrConvert.bytes");
			paths.Add("Config/Table/CSVAttrBoost.bytes");
			paths.Add("Config/Table/CSVAttr.bytes");
			paths.Add("Config/Table/CSVAssessType.bytes");
			paths.Add("Config/Table/CSVAssessScore.bytes");
			paths.Add("Config/Table/CSVAssessMain.bytes");
			paths.Add("Config/Table/CSVArenaWinAward.bytes");
			paths.Add("Config/Table/CSVArenaSegmentInformation.bytes");
			paths.Add("Config/Table/CSVArenaRankingAward.bytes");
			paths.Add("Config/Table/CSVArenaRandAward.bytes");
			paths.Add("Config/Table/CSVArenaMaxStars.bytes");
			paths.Add("Config/Table/CSVArenaCumlativeRewards.bytes");
			paths.Add("Config/Table/CSVArenaActNumperiods.bytes");
			paths.Add("Config/Table/CSVAreaProtectionParameters.bytes");
			paths.Add("Config/Table/CSVAreaProtection.bytes");
			paths.Add("Config/Table/CSVAnnouncement.bytes");
			paths.Add("Config/Table/CSVAllRaceBonus.bytes");
			paths.Add("Config/Table/CSVAidValue.bytes");
			paths.Add("Config/Table/CSVAidPoint.bytes");
			paths.Add("Config/Table/CSVAICharacter.bytes");
			paths.Add("Config/Table/CSVAiBubbleChat.bytes");
			paths.Add("Config/Table/CSVAdventureProgress.bytes");
			paths.Add("Config/Table/CSVAdventureMap.bytes");
			paths.Add("Config/Table/CSVAdventureLevel.bytes");
			paths.Add("Config/Table/CSVAdventureCriminal.bytes");
			paths.Add("Config/Table/CSVActivityUiJump.bytes");
			paths.Add("Config/Table/CSVActivityTime.bytes");
			paths.Add("Config/Table/CSVActivityTarget.bytes");
			paths.Add("Config/Table/CSVActivityShopGoods.bytes");
			paths.Add("Config/Table/CSVActivityShop.bytes");
			paths.Add("Config/Table/CSVActivityQuestGroup.bytes");
			paths.Add("Config/Table/CSVActivityMainUi.bytes");
			paths.Add("Config/Table/CSVActivityMainnUi.bytes");
			paths.Add("Config/Table/CSVActiveSkillShowId.bytes");
			paths.Add("Config/Table/CSVActiveSkillShow.bytes");
			paths.Add("Config/Table/CSVActiveSkillInfo.bytes");
			paths.Add("Config/Table/CSVActiveSkillEffective.bytes");
			paths.Add("Config/Table/CSVActiveSkillBehavior.bytes");
			paths.Add("Config/Table/CSVActiveSkill.bytes");
			paths.Add("Config/Table/CSVActiverEmergencySwitch.bytes");
			paths.Add("Config/Table/CSVActionState.bytes");
			paths.Add("Config/Table/CSVAction.bytes");
			paths.Add("Config/Table/CSVAchievementType.bytes");
			paths.Add("Config/Table/CSVAchievementLevel.bytes");
			paths.Add("Config/Table/CSVAchievementLanguage.bytes");
			paths.Add("Config/Table/CSVAchievementIconMix.bytes");
			paths.Add("Config/Table/CSVAchievementDrop.bytes");
			paths.Add("Config/Table/CSVAchievement.bytes");
			paths.Add("Config/Table/CSVAccruePay.bytes");
			paths.Add("Config/Table/CSVAccrueConsume.bytes");
			paths.Add("Config/Table/CSBiographyChapter.bytes");
			return paths;
		}
	}
}
